// vocab-data.js - TỔNG KHO DỮ LIỆU
const ieltsDatabase = {
    "travel": [
        { word: "Destination", type: "Noun", mean: "Điểm đến", example: "After ten hours of driving, we finally reached our destination.", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=400" },
        { word: "Itinerary", type: "Noun", mean: "Lịch trình", example: "We have a very tight itinerary for our three-day trip to Hanoi.", imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=400" },
        { word: "Accommodation", type: "Noun", mean: "Chỗ ở", example: "Hotel accommodation is included in the price of the tour.", imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=400" }
    ],
    "education": [
        { word: "Curriculum", type: "(n)", mean: "Chương trình học", example: "The school curriculum includes a wide range of subjects.", imageUrl: "./images/curriculum.jpg" },
        { word: "Syllabus", type: "(n)", mean: "Đề cương môn học", example: "Please refer to the syllabus for the exam dates.", imageUrl: "./images/syllabus.jpg" },
        { word: "Discipline", type: "(n)", mean: "Ngành học / kỷ luật", example: "Engineering is a challenging discipline.", imageUrl: "./images/discipline.png" },
        { word: "Pedagogy", type: "(n)", mean: "Phương pháp giảng dạy", example: "Modern pedagogy focuses on student engagement.", imageUrl: "./images/pedagogy.jpg" },
        { word: "Assessment", type: "(n)", mean: "Đánh giá", example: "Continuous assessment helps track student progress.", imageUrl: "./images/assessment.png" },
        { word: "Qualification", type: "(n)", mean: "Bằng cấp", example: "He has the right qualifications for the job.", imageUrl: "./images/qualification.jpg" },
        { word: "Academic performance", type: "(n)", mean: "Thành tích học tập", example: "His academic performance improved significantly.", imageUrl: "./images/academic_performance.png" },
        { word: "Compulsory", type: "(adj)", mean: "Bắt buộc", example: "Math and English are compulsory subjects.", imageUrl: "./images/compulsory.jpg" },
        { word: "Optional", type: "(adj)", mean: "Tự chọn", example: "Students can choose from several optional modules.", imageUrl: "./images/optional.jpg" },
        { word: "Extracurricular", type: "(adj)", mean: "Ngoại khóa", example: "Extracurricular activities help build soft skills.", imageUrl: "./images/extracurricular.jpg" },
        { word: "Self-directed learning", type: "(n)", mean: "Tự học", example: "Self-directed learning is key to success in university.", imageUrl: "./images/self_directed_learning.jpg" },
        { word: "Rote learning", type: "(n)", mean: "Học vẹt", example: "Rote learning is not as effective as understanding concepts.", imageUrl: "./images/rote_learning.png" },
        { word: "Critical thinking", type: "(n)", mean: "Tư duy phản biện", example: "University education encourages critical thinking.", imageUrl: "./images/critical_thinking.jpg" },
        { word: "Analytical skills", type: "(n)", mean: "Kỹ năng phân tích", example: "Engineers need strong analytical skills to solve problems.", imageUrl: "./images/analytical_skills.jpg" },
        { word: "Collaborative learning", type: "(n)", mean: "Học nhóm", example: "Collaborative learning allows students to share ideas.", imageUrl: "./images/collaborative_learning.jpg" },
        { word: "Student-centered approach", type: "(n)", mean: "Lấy học sinh làm trung tâm", example: "The teacher adopted a student-centered approach.", imageUrl: "./images/student_centered.jpg" },
        { word: "Theoretical knowledge", type: "(n)", mean: "Lý thuyết", example: "Theoretical knowledge should be combined with practice.", imageUrl: "./images/theoretical_knowledge.jpg" },
        { word: "Practical skills", type: "(n)", mean: "Kỹ năng thực hành", example: "Lab work is important for developing practical skills.", imageUrl: "./images/practical_skills.jpg" },
        { word: "Cognitive development", type: "(n)", mean: "Phát triển nhận thức", example: "Play is vital for a child's cognitive development.", imageUrl: "./images/cognitive_development.jpg" },
        { word: "Knowledge retention", type: "(n)", mean: "Khả năng ghi nhớ", example: "Active learning improves knowledge retention.", imageUrl: "./images/knowledge_retention.jpg" },
        { word: "Higher education", type: "(n)", mean: "Giáo dục đại học", example: "Higher education opens many career opportunities.", imageUrl: "./images/higher_education.png" },
        { word: "Vocational training", type: "(n)", mean: "Đào tạo nghề", example: "Vocational training focuses on specific job skills.", imageUrl: "./images/vocational_training.jpg" },
        { word: "Distance learning", type: "(n)", mean: "Học từ xa", example: "Distance learning is flexible for working students.", imageUrl: "./images/distance_learning.jpg" },
        { word: "Online learning", type: "(n)", mean: "Học trực tuyến", example: "Many universities now offer online platforms.", imageUrl: "./images/online_learning.jpg" },
        { word: "Educational inequality", type: "(n)", mean: "Bất bình đẳng giáo dục", example: "Governments should reduce educational inequality.", imageUrl: "./images/educational_inequality.jpg" },
        { word: "Tuition fees", type: "(n)", mean: "Học phí", example: "High tuition fees can be a barrier to entry.", imageUrl: "./images/tuition_fees.jpg" },
        { word: "Dropout rate", type: "(n)", mean: "Tỷ lệ bỏ học", example: "The university is trying to lower its dropout rate.", imageUrl: "./images/dropout_rate.jpg" },
        { word: "Literacy rate", type: "(n)", mean: "Tỷ lệ biết chữ", example: "The country's literacy rate has increased.", imageUrl: "./images/literacy_rate.jpg" },
        { word: "Academic pressure", type: "(n)", mean: "Áp lực học tập", example: "Students often face intense pressure during finals.", imageUrl: "./images/academic_pressure.jpg" },
        { word: "Holistic education", type: "(n)", mean: "Giáo dục toàn diện", example: "Holistic education develops both mind and character.", imageUrl: "./images/holistic_education.jpg" }
    ],
    "environment": [
        { word: "Climate change", type: "(n)", mean: "Biến đổi khí hậu", example: "Climate change is one of the most pressing global issues today.", imageUrl: "./images/climate_change.png" },
        { word: "Global warming", type: "(n)", mean: "Nóng lên toàn cầu", example: "Global warming is causing polar ice caps to melt at an alarming rate.", imageUrl: "./images/global_warming.png" },
        { word: "Air pollution", type: "(n)", mean: "Ô nhiễm không khí", example: "Strict regulations are needed to reduce air pollution in major cities.", imageUrl: "./images/air_pollution.png" },
        { word: "Water contamination", type: "(n)", mean: "Ô nhiễm nguồn nước", example: "Water contamination from factories poses a severe threat to marine life.", imageUrl: "./images/water_contamination.png" },
        { word: "Deforestation", type: "(n)", mean: "Nạn phá rừng", example: "Deforestation leads to soil erosion and loss of animal habitats.", imageUrl: "./images/deforestation.png" },
        { word: "Biodiversity loss", type: "(n)", mean: "Suy giảm đa dạng sinh học", example: "The destruction of the rainforest contributes significantly to biodiversity loss.", imageUrl: "./images/biodiversity_loss.png" },
        { word: "Habitat destruction", type: "(n)", mean: "Phá hủy môi trường sống", example: "Many species are endangered due to habitat destruction.", imageUrl: "./images/habitat_destruction.png" },
        { word: "Overpopulation", type: "(n)", mean: "Bùng nổ dân số", example: "Overpopulation puts immense pressure on natural resources and infrastructure.", imageUrl: "./images/overpopulation.png" },
        { word: "Waste accumulation", type: "(n)", mean: "Sự tích tụ rác thải", example: "Waste accumulation in landfills is a major environmental concern.", imageUrl: "./images/waste_accumulation.png" },
        { word: "Resource depletion", type: "(n)", mean: "Cạn kiệt tài nguyên", example: "The continuous reliance on fossil fuels accelerates resource depletion.", imageUrl: "./images/resource_depletion.png" },
        { word: "Renewable energy", type: "(n)", mean: "Năng lượng tái tạo", example: "Governments should invest more heavily in renewable energy sources like wind and solar.", imageUrl: "./images/renewable_energy.png" },
        { word: "Sustainable development", type: "(n)", mean: "Phát triển bền vững", example: "Sustainable development ensures economic growth without harming the environment.", imageUrl: "./images/sustainable_development.png" },
        { word: "Carbon footprint", type: "(n)", mean: "Lượng khí thải carbon", example: "Using public transport is an effective way to reduce your carbon footprint.", imageUrl: "./images/carbon_footprint.png" },
        { word: "Recycling", type: "(n)", mean: "Tái chế", example: "Promoting a culture of recycling can significantly reduce household waste.", imageUrl: "./images/recycling.png" },
        { word: "Waste management", type: "(n)", mean: "Quản lý rác thải", example: "Effective waste management systems are vital for rapidly growing urban areas.", imageUrl: "./images/waste_management.png" },
        { word: "Energy conservation", type: "(n)", mean: "Tiết kiệm năng lượng", example: "Energy conservation measures can lower electricity bills and protect nature.", imageUrl: "./images/energy_conservation.png" },
        { word: "Eco-friendly", type: "(adj)", mean: "Thân thiện với môi trường", example: "Many consumers now prefer to buy eco-friendly products to reduce waste.", imageUrl: "./images/eco_friendly.png" },
        { word: "Green technology", type: "(n)", mean: "Công nghệ xanh", example: "Advances in green technology are essential for combating climate change.", imageUrl: "./images/green_technology.png" },
        { word: "Environmental protection", type: "(n)", mean: "Bảo vệ môi trường", example: "Environmental protection should be prioritized over short-term economic gains.", imageUrl: "./images/environmental_protection.png" },
        { word: "Conservation", type: "(n)", mean: "Bảo tồn", example: "Wildlife conservation programs help protect endangered species from extinction.", imageUrl: "./images/conservation.png" },
        { word: "Industrial emissions", type: "(n)", mean: "Khí thải công nghiệp", example: "Factories must install filters to reduce harmful industrial emissions.", imageUrl: "./images/industrial_emissions.png" },
        { word: "Fossil fuels", type: "(n)", mean: "Nhiên liệu hóa thạch", example: "Burning fossil fuels is the primary driver of the greenhouse effect.", imageUrl: "./images/fossil_fuels.png" },
        { word: "Urbanization", type: "(n)", mean: "Đô thị hóa", example: "Rapid urbanization has led to the loss of agricultural land around the city.", imageUrl: "./images/urbanization.png" },
        { word: "Agricultural runoff", type: "(n)", mean: "Nước thải nông nghiệp", example: "Agricultural runoff containing pesticides can severely pollute local rivers.", imageUrl: "./images/agricultural_runoff.png" },
        { word: "Illegal logging", type: "(n)", mean: "Khai thác gỗ trái phép", example: "Strict penalties must be enforced to stop illegal logging in national parks.", imageUrl: "./images/illegal_logging.png" },
        { word: "Overconsumption", type: "(n)", mean: "Tiêu thụ quá mức", example: "Our culture of overconsumption is rapidly depleting the Earth's natural resources.", imageUrl: "./images/overconsumption.png" },
        { word: "Plastic waste", type: "(n)", mean: "Rác thải nhựa", example: "Marine life is severely threatened by the sheer volume of plastic waste in the oceans.", imageUrl: "./images/plastic_waste.png" },
        { word: "Greenhouse gases", type: "(n)", mean: "Khí nhà kính", example: "Carbon dioxide and methane are the most prominent greenhouse gases.", imageUrl: "./images/greenhouse_gases.png" },
        { word: "Land degradation", type: "(n)", mean: "Thoái hóa đất", example: "Intensive farming practices often lead to severe land degradation over time.", imageUrl: "./images/land_degradation.png" },
        { word: "Toxic waste", type: "(n)", mean: "Chất thải độc hại", example: "Safe disposal of toxic waste is required by strict environmental laws.", imageUrl: "./images/toxic_waste.png" }
    ],
    "health": [
        { word: "Balanced diet", type: "(n)", mean: "Chế độ ăn cân bằng", example: "Maintaining a balanced diet is crucial for a healthy lifestyle.", imageUrl: "./images/balanced_diet.png" },
        { word: "Nutrient-rich", type: "(adj)", mean: "Giàu dinh dưỡng", example: "You should include more nutrient-rich foods like spinach in your meals.", imageUrl: "./images/nutrient_rich.png" },
        { word: "Well-being", type: "(n)", mean: "Sức khỏe tổng thể", example: "Yoga and meditation can significantly improve your overall well-being.", imageUrl: "./images/well_being.png" },
        { word: "Physical fitness", type: "(n)", mean: "Thể lực", example: "Regular training is required to achieve a high level of physical fitness.", imageUrl: "./images/physical_fitness.png" },
        { word: "Regular exercise", type: "(n)", mean: "Tập thể dục đều đặn", example: "Regular exercise helps to reduce the risk of heart disease.", imageUrl: "./images/regular_exercise.png" },
        { word: "Healthy habits", type: "(n)", mean: "Thói quen lành mạnh", example: "Developing healthy habits early in life can prevent future illnesses.", imageUrl: "./images/healthy_habits.png" },
        { word: "Lifestyle choices", type: "(n)", mean: "Lựa chọn lối sống", example: "Our daily lifestyle choices have a direct impact on our lifespan.", imageUrl: "./images/lifestyle_choices.png" },
        { word: "Preventive healthcare", type: "(n)", mean: "Chăm sóc sức khỏe phòng ngừa", example: "Preventive healthcare focuses on preventing diseases rather than treating them.", imageUrl: "./images/preventive_healthcare.png" },
        { word: "Immune system", type: "(n)", mean: "Hệ miễn dịch", example: "Eating plenty of fruits and vegetables strengthens the immune system.", imageUrl: "./images/immune_system.png" },
        { word: "Mental health", type: "(n)", mean: "Sức khỏe tinh thần", example: "Mental health is just as important as physical health.", imageUrl: "./images/mental_health.png" },
        { word: "Calorie intake", type: "(n)", mean: "Lượng calo nạp vào", example: "People trying to lose weight need to monitor their daily calorie intake.", imageUrl: "./images/calorie_intake.png" },
        { word: "Processed food", type: "(n)", mean: "Thực phẩm chế biến sẵn", example: "Consuming too much processed food can lead to serious health problems.", imageUrl: "./images/processed_food.png" },
        { word: "Junk food", type: "(n)", mean: "Đồ ăn nhanh", example: "Parents should limit the amount of junk food their children eat.", imageUrl: "./images/junk_food.png" },
        { word: "Sugar consumption", type: "(n)", mean: "Lượng tiêu thụ đường", example: "High sugar consumption is strongly linked to type 2 diabetes.", imageUrl: "./images/sugar_consumption.png" },
        { word: "Organic food", type: "(n)", mean: "Thực phẩm hữu cơ", example: "Many people prefer organic food because it is free from pesticides.", imageUrl: "./images/organic_food.png" },
        { word: "Dietary fiber", type: "(n)", mean: "Chất xơ", example: "Foods rich in dietary fiber are good for your digestive system.", imageUrl: "./images/dietary_fiber.png" },
        { word: "Vitamin deficiency", type: "(n)", mean: "Thiếu vitamin", example: "Vitamin deficiency can cause various health issues like fatigue.", imageUrl: "./images/vitamin_deficiency.png" },
        { word: "Malnutrition", type: "(n)", mean: "Suy dinh dưỡng", example: "Malnutrition remains a serious problem in many developing countries.", imageUrl: "./images/malnutrition.png" },
        { word: "Hydration", type: "(n)", mean: "Sự cung cấp đủ nước", example: "Proper hydration is essential, especially after a heavy workout.", imageUrl: "./images/hydration.png" },
        { word: "Portion control", type: "(n)", mean: "Kiểm soát khẩu phần ăn", example: "Portion control is an effective strategy for weight management.", imageUrl: "./images/portion_control.png" },
        { word: "Obesity", type: "(n)", mean: "Béo phì", example: "Childhood obesity has become a major public health concern globally.", imageUrl: "./images/obesity.png" },
        { word: "Sedentary lifestyle", type: "(n)", mean: "Lối sống ít vận động", example: "A sedentary lifestyle is a major risk factor for cardiovascular diseases.", imageUrl: "./images/sedentary_lifestyle.png" },
        { word: "Chronic disease", type: "(n)", mean: "Bệnh mãn tính", example: "Smoking significantly increases the risk of developing a chronic disease.", imageUrl: "./images/chronic_disease.png" },
        { word: "Cardiovascular disease", type: "(n)", mean: "Bệnh tim mạch", example: "Cardiovascular disease is one of the leading causes of death worldwide.", imageUrl: "./images/cardiovascular_disease.png" },
        { word: "Stress management", type: "(n)", mean: "Quản lý căng thẳng", example: "Effective stress management techniques include deep breathing and meditation.", imageUrl: "./images/stress_management.png" },
        { word: "Sleep deprivation", type: "(n)", mean: "Thiếu ngủ", example: "Chronic sleep deprivation can negatively affect your concentration and mood.", imageUrl: "./images/sleep_deprivation.png" },
        { word: "Addiction", type: "(n)", mean: "Nghiện", example: "Smartphone addiction is becoming increasingly common among teenagers.", imageUrl: "./images/addiction.png" },
        { word: "Public health", type: "(n)", mean: "Y tế cộng đồng", example: "The government needs to invest more money in public health campaigns.", imageUrl: "./images/public_health.png" },
        { word: "Health awareness", type: "(n)", mean: "Nhận thức về sức khỏe", example: "Schools play a vital role in raising health awareness among students.", imageUrl: "./images/health_awareness.png" },
        { word: "Medical treatment", type: "(n)", mean: "Điều trị y tế", example: "Patients with severe symptoms should seek immediate medical treatment.", imageUrl: "./images/medical_treatment.png" }
    ],
    "family": [
        { word: "Nuclear family", type: "(n)", mean: "Gia đình hạt nhân", example: "The nuclear family is the most common family structure in modern society.", imageUrl: "./images/nuclear_family.png" },
        { word: "Extended family", type: "(n)", mean: "Gia đình nhiều thế hệ", example: "Growing up in an extended family helps children learn how to share.", imageUrl: "./images/extended_family.png" },
        { word: "Single-parent family", type: "(n)", mean: "Gia đình đơn thân", example: "Financial support is crucial for children in a single-parent family.", imageUrl: "./images/single_parent_family.png" },
        { word: "Household", type: "(n)", mean: "Hộ gia đình", example: "The average size of a household has decreased in recent years.", imageUrl: "./images/household.png" },
        { word: "Breadwinner", type: "(n)", mean: "Trụ cột gia đình", example: "Traditionally, the father was the main breadwinner of the family.", imageUrl: "./images/breadwinner.png" },
        { word: "Dependents", type: "(n)", mean: "Người phụ thuộc", example: "Employees can claim tax deductions if they have dependents.", imageUrl: "./images/dependents.png" },
        { word: "Sibling", type: "(n)", mean: "Anh/chị/em ruột", example: "I have a close relationship with my younger sibling.", imageUrl: "./images/sibling.png" },
        { word: "Only child", type: "(n)", mean: "Con một", example: "Being an only child means you get all of your parents' attention.", imageUrl: "./images/only_child.png" },
        { word: "Generation gap", type: "(n)", mean: "Khoảng cách thế hệ", example: "The generation gap can cause misunderstandings about technology.", imageUrl: "./images/generation_gap.png" },
        { word: "Family-oriented", type: "(adj)", mean: "Coi trọng gia đình", example: "He is a family-oriented man who always prioritizes his children.", imageUrl: "./images/family_oriented.png" },
        { word: "Close-knit", type: "(adj)", mean: "Gắn bó khăng khít", example: "We are a close-knit family and support each other through hard times.", imageUrl: "./images/close_knit.png" },
        { word: "Parental guidance", type: "(n)", mean: "Sự định hướng của cha mẹ", example: "Proper parental guidance is essential for a teenager's development.", imageUrl: "./images/parental_guidance.png" },
        { word: "Emotional support", type: "(n)", mean: "Hỗ trợ tinh thần", example: "Family provides the emotional support needed to overcome stress.", imageUrl: "./images/emotional_support.png" },
        { word: "Mutual respect", type: "(n)", mean: "Sự tôn trọng lẫn nhau", example: "A healthy marriage is built on trust and mutual respect.", imageUrl: "./images/mutual_respect.png" },
        { word: "Family bond", type: "(n)", mean: "Mối liên kết gia đình", example: "Having dinner together every night strengthens the family bond.", imageUrl: "./images/family_bond.png" },
        { word: "Upbringing", type: "(n)", mean: "Sự nuôi dạy", example: "A strict upbringing shaped his disciplined approach to studying.", imageUrl: "./images/upbringing.png" },
        { word: "Discipline", type: "(n)", mean: "Sự kỷ luật", example: "Parents should enforce discipline without using physical punishment.", imageUrl: "./images/discipline.png" },
        { word: "Caregiver", type: "(n)", mean: "Người chăm sóc", example: "The mother is usually the primary caregiver in the early years.", imageUrl: "./images/caregiver.png" },
        { word: "Role model", type: "(n)", mean: "Hình mẫu", example: "Teachers often serve as important role models for their students.", imageUrl: "./images/role_model.png" },
        { word: "Household responsibilities", type: "(n)", mean: "Trách nhiệm trong gia đình", example: "Children should learn to share household responsibilities.", imageUrl: "./images/household_responsibilities.png" },
        { word: "Divorce rate", type: "(n)", mean: "Tỷ lệ ly hôn", example: "The divorce rate has increased due to modern lifestyle pressures.", imageUrl: "./images/divorce_rate.png" },
        { word: "Work-life balance", type: "(n)", mean: "Cân bằng công việc - cuộc sống", example: "Maintaining a healthy work-life balance reduces domestic conflict.", imageUrl: "./images/work_life_balance.png" },
        { word: "Domestic conflict", type: "(n)", mean: "Mâu thuẫn gia đình", example: "Financial issues are a common cause of domestic conflict.", imageUrl: "./images/domestic_conflict.png" },
        { word: "Child neglect", type: "(n)", mean: "Bỏ bê con cái", example: "Child neglect can have severe long-term psychological effects.", imageUrl: "./images/child_neglect.png" },
        { word: "Financial burden", type: "(n)", mean: "Gánh nặng tài chính", example: "University tuition fees can be a huge financial burden for families.", imageUrl: "./images/financial_burden.png" },
        { word: "Parenting style", type: "(n)", mean: "Phong cách nuôi dạy con", example: "Different cultures have completely different parenting styles.", imageUrl: "./images/parenting_style.png" },
        { word: "Generation differences", type: "(n)", mean: "Khác biệt thế hệ", example: "Generation differences are most obvious in musical tastes.", imageUrl: "./images/generation_differences.png" },
        { word: "Aging population", type: "(n)", mean: "Dân số già hóa", example: "An aging population puts pressure on the healthcare system.", imageUrl: "./images/aging_population.png" },
        { word: "Family values", type: "(n)", mean: "Giá trị gia đình", example: "Traditional family values are still respected in many Asian societies.", imageUrl: "./images/family_values.png" },
        { word: "Quality time", type: "(n)", mean: "Thời gian chất lượng", example: "Spending quality time with children is more important than buying them gifts.", imageUrl: "./images/quality_time.png" }
    ],
    "travel": [
        { word: "Domestic travel", type: "(n)", mean: "Du lịch trong nước", example: "Domestic travel has recovered faster than international flights.", imageUrl: "./images/domestic_travel.png" },
        { word: "International travel", type: "(n)", mean: "Du lịch quốc tế", example: "International travel exposes you to different cultures and languages.", imageUrl: "./images/international_travel.png" },
        { word: "Eco-tourism", type: "(n)", mean: "Du lịch sinh thái", example: "Eco-tourism helps protect the environment and supports local communities.", imageUrl: "./images/eco_tourism.png" },
        { word: "Mass tourism", type: "(n)", mean: "Du lịch đại trà", example: "Mass tourism can cause severe damage to historical sites.", imageUrl: "./images/mass_tourism.png" },
        { word: "Backpacking", type: "(n)", mean: "Du lịch bụi", example: "Backpacking is a popular way for students to explore the world cheaply.", imageUrl: "./images/backpacking.png" },
        { word: "Package tour", type: "(n)", mean: "Tour trọn gói", example: "Many older people prefer the convenience of a package tour.", imageUrl: "./images/package_tour.png" },
        { word: "Solo travel", type: "(n)", mean: "Du lịch một mình", example: "Solo travel forces you to step out of your comfort zone.", imageUrl: "./images/solo_travel.png" },
        { word: "Business trip", type: "(n)", mean: "Chuyến công tác", example: "Engineers often go on business trips to inspect new facilities.", imageUrl: "./images/business_trip.png" },
        { word: "Long-haul flight", type: "(n)", mean: "Chuyến bay đường dài", example: "Make sure to drink plenty of water during a long-haul flight.", imageUrl: "./images/long_haul_flight.png" },
        { word: "Short getaway", type: "(n)", mean: "Chuyến đi ngắn ngày", example: "We went on a short getaway to the mountains to relax.", imageUrl: "./images/short_getaway.png" },
        { word: "Itinerary", type: "(n)", mean: "Lịch trình", example: "Our itinerary includes a visit to the local museum.", imageUrl: "./images/itinerary.png" },
        { word: "Accommodation", type: "(n)", mean: "Chỗ ở", example: "Booking accommodation in advance is highly recommended.", imageUrl: "./images/accommodation.png" },
        { word: "Hospitality", type: "(n)", mean: "Sự hiếu khách", example: "The locals are famous for their warm hospitality.", imageUrl: "./images/hospitality.png" },
        { word: "Tourist attraction", type: "(n)", mean: "Điểm du lịch", example: "The Eiffel Tower is a major tourist attraction in Paris.", imageUrl: "./images/tourist_attraction.png" },
        { word: "Scenic views", type: "(n)", mean: "Cảnh đẹp", example: "The hotel room offers stunning scenic views of the ocean.", imageUrl: "./images/scenic_views.png" },
        { word: "Local cuisine", type: "(n)", mean: "Ẩm thực địa phương", example: "Trying the local cuisine is an essential part of any trip.", imageUrl: "./images/local_cuisine.png" },
        { word: "Cultural experience", type: "(n)", mean: "Trải nghiệm văn hóa", example: "Attending the festival was a fantastic cultural experience.", imageUrl: "./images/cultural_experience.png" },
        { word: "Travel insurance", type: "(n)", mean: "Bảo hiểm du lịch", example: "You should always buy travel insurance before going abroad.", imageUrl: "./images/travel_insurance.png" },
        { word: "Jet lag", type: "(n)", mean: "Lệch múi giờ", example: "It took me three days to recover from the jet lag.", imageUrl: "./images/jet_lag.png" },
        { word: "Travel essentials", type: "(n)", mean: "Vật dụng cần thiết", example: "A passport and a charger are absolute travel essentials.", imageUrl: "./images/travel_essentials.png" },
        { word: "Overcrowding", type: "(n)", mean: "Quá tải", example: "Overcrowding in famous cities ruins the experience for many visitors.", imageUrl: "./images/overcrowding.png" },
        { word: "Tourist hotspot", type: "(n)", mean: "Điểm du lịch nổi tiếng", example: "During summer, the beach becomes a busy tourist hotspot.", imageUrl: "./images/tourist_hotspot.png" },
        { word: "Environmental impact", type: "(n)", mean: "Tác động môi trường", example: "Air travel has a significant environmental impact.", imageUrl: "./images/environmental_impact.png" },
        { word: "Sustainable tourism", type: "(n)", mean: "Du lịch bền vững", example: "Sustainable tourism minimizes carbon emissions and waste.", imageUrl: "./images/sustainable_tourism.png" },
        { word: "Cultural preservation", type: "(n)", mean: "Bảo tồn văn hóa", example: "Tourism revenue can be used for cultural preservation.", imageUrl: "./images/cultural_preservation.png" },
        { word: "Travel restrictions", type: "(n)", mean: "Hạn chế đi lại", example: "New travel restrictions were implemented due to the virus outbreak.", imageUrl: "./images/travel_restrictions.png" },
        { word: "Carbon emissions", type: "(n)", mean: "Khí thải carbon", example: "Aviation contributes heavily to global carbon emissions.", imageUrl: "./images/carbon_emissions.png" },
        { word: "Tourism industry", type: "(n)", mean: "Ngành du lịch", example: "The tourism industry provides millions of jobs worldwide.", imageUrl: "./images/tourism_industry.png" },
        { word: "Economic boost", type: "(n)", mean: "Thúc đẩy kinh tế", example: "Hosting the Olympics provided a major economic boost for the city.", imageUrl: "./images/economic_boost.png" },
        { word: "Peak season", type: "(n)", mean: "Mùa cao điểm", example: "Flights and hotels are much more expensive during the peak season.", imageUrl: "./images/peak_season.png" }
    ],
    "technology": [
        { word: "Cutting-edge technology", type: "(n)", mean: "Công nghệ tiên tiến", example: "The laboratory is equipped with cutting-edge technology.", imageUrl: "./images/cutting_edge_technology.png" },
        { word: "Technological advancement", type: "(n)", mean: "Tiến bộ công nghệ", example: "Technological advancement has dramatically changed how we study.", imageUrl: "./images/technological_advancement.png" },
        { word: "Digital transformation", type: "(n)", mean: "Chuyển đổi số", example: "Many businesses underwent rapid digital transformation recently.", imageUrl: "./images/digital_transformation.png" },
        { word: "Innovation", type: "(n)", mean: "Đổi mới", example: "Innovation is key to surviving in a competitive market.", imageUrl: "./images/innovation_tech.png" },
        { word: "Automation", type: "(n)", mean: "Tự động hóa", example: "Automation is highly applied in modern thermal and mechanical systems.", imageUrl: "./images/automation.png" },
        { word: "Artificial intelligence", type: "(n)", mean: "Trí tuệ nhân tạo", example: "Artificial intelligence is capable of solving complex engineering problems.", imageUrl: "./images/artificial_intelligence.png" },
        { word: "Machine learning", type: "(n)", mean: "Học máy", example: "Machine learning algorithms improve themselves through experience.", imageUrl: "./images/machine_learning.png" },
        { word: "Data analytics", type: "(n)", mean: "Phân tích dữ liệu", example: "Data analytics helps companies understand consumer behavior.", imageUrl: "./images/data_analytics.png" },
        { word: "Cloud computing", type: "(n)", mean: "Điện toán đám mây", example: "Cloud computing allows us to access files from anywhere.", imageUrl: "./images/cloud_computing.png" },
        { word: "Cybersecurity", type: "(n)", mean: "An ninh mạng", example: "Cybersecurity is crucial to protect sensitive personal information.", imageUrl: "./images/cybersecurity.png" },
        { word: "Smart device", type: "(n)", mean: "Thiết bị thông minh", example: "Almost every student now owns at least one smart device.", imageUrl: "./images/smart_device.png" },
        { word: "High-speed internet", type: "(n)", mean: "Internet tốc độ cao", example: "High-speed internet is essential for uninterrupted virtual meetings.", imageUrl: "./images/high_speed_internet.png" },
        { word: "Social media platforms", type: "(n)", mean: "Nền tảng mạng xã hội", example: "Social media platforms can be highly addictive for teenagers.", imageUrl: "./images/social_media_platforms.png" },
        { word: "Online privacy", type: "(n)", mean: "Quyền riêng tư trực tuyến", example: "Users must be careful about their online privacy settings.", imageUrl: "./images/online_privacy.png" },
        { word: "Data breach", type: "(n)", mean: "Rò rỉ dữ liệu", example: "A recent data breach exposed the passwords of millions of users.", imageUrl: "./images/data_breach.png" },
        { word: "Digital footprint", type: "(n)", mean: "Dấu vết số", example: "Employers often research a candidate's digital footprint.", imageUrl: "./images/digital_footprint.png" },
        { word: "Screen time", type: "(n)", mean: "Thời gian dùng màn hình", example: "Parents should limit their children's daily screen time.", imageUrl: "./images/screen_time.png" },
        { word: "Internet addiction", type: "(n)", mean: "Nghiện internet", example: "Internet addiction can severely affect academic performance.", imageUrl: "./images/internet_addiction.png" },
        { word: "Virtual meeting", type: "(n)", mean: "Họp trực tuyến", example: "Virtual meetings save a lot of time and travel expenses.", imageUrl: "./images/virtual_meeting.png" },
        { word: "Remote work", type: "(n)", mean: "Làm việc từ xa", example: "Remote work offers flexibility but requires strong self-discipline.", imageUrl: "./images/remote_work.png" },
        { word: "Job displacement", type: "(n)", mean: "Mất việc do công nghệ", example: "Automation in factories often leads to job displacement.", imageUrl: "./images/job_displacement.png" },
        { word: "Digital divide", type: "(n)", mean: "Khoảng cách số", example: "The government must invest in education to bridge the digital divide.", imageUrl: "./images/digital_divide.png" },
        { word: "Information overload", type: "(n)", mean: "Quá tải thông tin", example: "Constant notifications can easily cause information overload.", imageUrl: "./images/information_overload.png" },
        { word: "Technological dependency", type: "(n)", mean: "Phụ thuộc công nghệ", example: "Technological dependency makes us vulnerable to system failures.", imageUrl: "./images/technological_dependency.png" },
        { word: "Privacy concerns", type: "(n)", mean: "Lo ngại quyền riêng tư", example: "The new tracking app has raised serious privacy concerns.", imageUrl: "./images/privacy_concerns.png" },
        { word: "Ethical issues", type: "(n)", mean: "Vấn đề đạo đức", example: "Cloning technology brings up many complex ethical issues.", imageUrl: "./images/ethical_issues.png" },
        { word: "Automation risk", type: "(n)", mean: "Rủi ro tự động hóa", example: "Manual laborers face the highest automation risk.", imageUrl: "./images/automation_risk.png" },
        { word: "Productivity boost", type: "(n)", mean: "Tăng năng suất", example: "New software provided a significant productivity boost for the team.", imageUrl: "./images/productivity_boost.png" },
        { word: "User-friendly", type: "(adj)", mean: "Thân thiện người dùng", example: "The interface of the application is designed to be user-friendly.", imageUrl: "./images/user_friendly.png" },
        { word: "Time-consuming", type: "(adj)", mean: "Tốn thời gian", example: "Processing large datasets manually is incredibly time-consuming.", imageUrl: "./images/time_consuming.png" }
    ],
    "sports": [
        { word: "Competitive sports", type: "(n)", mean: "Thể thao thi đấu", example: "Participating in competitive sports teaches children how to handle loss.", imageUrl: "./images/competitive_sports.png" },
        { word: "Team sports", type: "(n)", mean: "Thể thao đồng đội", example: "Team sports like basketball develop strong communication skills.", imageUrl: "./images/team_sports.png" },
        { word: "Individual sports", type: "(n)", mean: "Thể thao cá nhân", example: "Individual sports require a high degree of self-motivation.", imageUrl: "./images/individual_sports.png" },
        { word: "Extreme sports", type: "(n)", mean: "Thể thao mạo hiểm", example: "Extreme sports carry a high risk of serious injury.", imageUrl: "./images/extreme_sports.png" },
        { word: "Water sports", type: "(n)", mean: "Thể thao dưới nước", example: "Surfing and diving are popular water sports in coastal areas.", imageUrl: "./images/water_sports.png" },
        { word: "Indoor sports", type: "(n)", mean: "Thể thao trong nhà", example: "Badminton is one of the most common indoor sports.", imageUrl: "./images/indoor_sports.png" },
        { word: "Outdoor activities", type: "(n)", mean: "Hoạt động ngoài trời", example: "Hiking and camping are great outdoor activities for the weekend.", imageUrl: "./images/outdoor_activities.png" },
        { word: "Physical activity", type: "(n)", mean: "Hoạt động thể chất", example: "Daily physical activity is necessary to maintain good health.", imageUrl: "./images/physical_activity.png" },
        { word: "Recreational sports", type: "(n)", mean: "Thể thao giải trí", example: "Many people play recreational sports simply to relieve stress.", imageUrl: "./images/recreational_sports.png" },
        { word: "Professional athlete", type: "(n)", mean: "Vận động viên chuyên nghiệp", example: "A professional athlete must follow a strict diet and training regime.", imageUrl: "./images/professional_athlete.png" },
        { word: "Physical endurance", type: "(n)", mean: "Sức bền", example: "Marathon runners need incredible physical endurance.", imageUrl: "./images/physical_endurance.png" },
        { word: "Muscle strength", type: "(n)", mean: "Sức mạnh cơ bắp", example: "Weightlifting is designed to increase muscle strength.", imageUrl: "./images/muscle_strength.png" },
        { word: "Stamina", type: "(n)", mean: "Thể lực", example: "You need good stamina to play a full 90-minute football match.", imageUrl: "./images/stamina.png" },
        { word: "Intensive training", type: "(n)", mean: "Luyện tập cường độ cao", example: "The team underwent intensive training before the championship.", imageUrl: "./images/intensive_training.png" },
        { word: "Workout routine", type: "(n)", mean: "Lịch tập", example: "Sticking to a daily workout routine yields the best results.", imageUrl: "./images/workout_routine.png" },
        { word: "Fitness level", type: "(n)", mean: "Mức thể lực", example: "The exercises can be adjusted to suit your personal fitness level.", imageUrl: "./images/fitness_level.png" },
        { word: "Warm-up", type: "(n/v)", mean: "Khởi động", example: "A proper warm-up prevents muscle cramps during exercise.", imageUrl: "./images/warm_up.png" },
        { word: "Cool down", type: "(n/v)", mean: "Thả lỏng", example: "It is important to cool down and stretch after a heavy workout.", imageUrl: "./images/cool_down.png" },
        { word: "Injury prevention", type: "(n)", mean: "Phòng tránh chấn thương", example: "Wearing the right shoes is crucial for injury prevention.", imageUrl: "./images/injury_prevention.png" },
        { word: "Personal trainer", type: "(n)", mean: "Huấn luyện viên cá nhân", example: "A personal trainer can help correct your lifting posture.", imageUrl: "./images/personal_trainer.png" },
        { word: "Boost immunity", type: "(v)", mean: "Tăng miễn dịch", example: "Regular exercise helps boost immunity against common illnesses.", imageUrl: "./images/boost_immunity.png" },
        { word: "Mental well-being", type: "(n)", mean: "Sức khỏe tinh thần", example: "Sports have a profoundly positive impact on mental well-being.", imageUrl: "./images/mental_well_being.png" },
        { word: "Stress relief", type: "(n)", mean: "Giảm căng thẳng", example: "Swimming serves as an excellent form of stress relief.", imageUrl: "./images/stress_relief.png" },
        { word: "Sedentary lifestyle", type: "(n)", mean: "Lối sống ít vận động", example: "A sedentary lifestyle is a major cause of modern health problems.", imageUrl: "./images/sedentary_lifestyle.png" },
        { word: "Sportsmanship", type: "(n)", mean: "Tinh thần thể thao", example: "Shaking hands after a match is a sign of good sportsmanship.", imageUrl: "./images/sportsmanship.png" },
        { word: "Fair play", type: "(n)", mean: "Chơi đẹp", example: "Referees are there to ensure fair play on the field.", imageUrl: "./images/fair_play.png" },
        { word: "Performance-enhancing drugs", type: "(n)", mean: "Chất kích thích", example: "Using performance-enhancing drugs will result in a lifetime ban.", imageUrl: "./images/performance_enhancing_drugs.png" },
        { word: "Match-fixing", type: "(n)", mean: "Dàn xếp tỉ số", example: "Several players were investigated for suspected match-fixing.", imageUrl: "./images/match_fixing.png" },
        { word: "Fan base", type: "(n)", mean: "Lượng người hâm mộ", example: "The football club has a massive international fan base.", imageUrl: "./images/fan_base.png" },
        { word: "Sports industry", type: "(n)", mean: "Ngành thể thao", example: "The global sports industry generates billions of dollars annually.", imageUrl: "./images/sports_industry.png" }
    ],
    "music": [
        { word: "Classical music", type: "(n)", mean: "Nhạc cổ điển", example: "Listening to classical music can help improve concentration.", imageUrl: "./images/classical_music.png" },
        { word: "Pop music", type: "(n)", mean: "Nhạc pop", example: "Pop music usually features catchy melodies and simple lyrics.", imageUrl: "./images/pop_music.png" },
        { word: "Rock music", type: "(n)", mean: "Nhạc rock", example: "Rock music is characterized by heavy beats and electric guitars.", imageUrl: "./images/rock_music.png" },
        { word: "Jazz", type: "(n)", mean: "Nhạc jazz", example: "Jazz is a genre that relies heavily on instrumental improvisation.", imageUrl: "./images/jazz.png" },
        { word: "Hip-hop", type: "(n)", mean: "Hip hop", example: "Hip-hop culture has deeply influenced modern fashion trends.", imageUrl: "./images/hip_hop.png" },
        { word: "Electronic music", type: "(n)", mean: "Nhạc điện tử", example: "Electronic music is very popular in nightclubs and festivals.", imageUrl: "./images/electronic_music.png" },
        { word: "Folk music", type: "(n)", mean: "Nhạc dân gian", example: "Folk music often tells stories about the daily lives of ordinary people.", imageUrl: "./images/folk_music.png" },
        { word: "Traditional music", type: "(n)", mean: "Nhạc truyền thống", example: "Traditional music is an integral part of national identity.", imageUrl: "./images/traditional_music.png" },
        { word: "Instrumental music", type: "(n)", mean: "Nhạc không lời", example: "Many students prefer studying while listening to instrumental music.", imageUrl: "./images/instrumental_music.png" },
        { word: "Live music", type: "(n)", mean: "Nhạc trực tiếp", example: "The atmosphere of a live music concert is truly electrifying.", imageUrl: "./images/live_music.png" },
        { word: "Melody", type: "(n)", mean: "Giai điệu", example: "The song has a beautiful and melancholic melody.", imageUrl: "./images/melody.png" },
        { word: "Rhythm", type: "(n)", mean: "Nhịp điệu", example: "You naturally want to dance when you hear a strong rhythm.", imageUrl: "./images/rhythm.png" },
        { word: "Lyrics", type: "(n)", mean: "Lời bài hát", example: "The lyrics of this song convey a powerful message about love.", imageUrl: "./images/lyrics.png" },
        { word: "Harmony", type: "(n)", mean: "Hòa âm", example: "The two singers' voices blended in perfect harmony.", imageUrl: "./images/harmony.png" },
        { word: "Vocal range", type: "(n)", mean: "Quãng giọng", example: "She is famous for her impressive vocal range.", imageUrl: "./images/vocal_range.png" },
        { word: "Pitch", type: "(n)", mean: "Cao độ", example: "The singer struggled to hit the high pitch during the chorus.", imageUrl: "./images/pitch.png" },
        { word: "Tone", type: "(n)", mean: "Âm sắc", example: "His voice has a very warm and soothing tone.", imageUrl: "./images/tone.png" },
        { word: "Composition", type: "(n)", mean: "Sáng tác", example: "This musical composition was written in the 18th century.", imageUrl: "./images/composition.png" },
        { word: "Live performance", type: "(n)", mean: "Biểu diễn trực tiếp", example: "A live performance allows artists to connect with their fans.", imageUrl: "./images/live_performance.png" },
        { word: "Music festival", type: "(n)", mean: "Lễ hội âm nhạc", example: "Thousands of young people gather for the outdoor music festival.", imageUrl: "./images/music_festival.png" },
        { word: "Music industry", type: "(n)", mean: "Ngành âm nhạc", example: "The internet has completely transformed the music industry.", imageUrl: "./images/music_industry.png" },
        { word: "Streaming platform", type: "(n)", mean: "Nền tảng nghe nhạc", example: "Artists now earn most of their revenue through streaming platforms.", imageUrl: "./images/streaming_platform.png" },
        { word: "Digital download", type: "(n)", mean: "Tải nhạc", example: "Sales of physical CDs have fallen due to digital downloads.", imageUrl: "./images/digital_download.png" },
        { word: "Copyright infringement", type: "(n)", mean: "Vi phạm bản quyền", example: "Sharing music files for free is considered copyright infringement.", imageUrl: "./images/copyright_infringement.png" },
        { word: "Musical taste", type: "(n)", mean: "Gu âm nhạc", example: "People's musical taste often changes as they grow older.", imageUrl: "./images/musical_taste.png" },
        { word: "Emotional expression", type: "(n)", mean: "Biểu đạt cảm xúc", example: "Music is a universal language for emotional expression.", imageUrl: "./images/emotional_expression.png" },
        { word: "Stress relief", type: "(n)", mean: "Giảm stress", example: "Playing an instrument provides an excellent outlet for stress relief.", imageUrl: "./images/stress_relief_music.png" },
        { word: "Cultural identity", type: "(n)", mean: "Bản sắc văn hóa", example: "Indigenous music helps preserve a community's cultural identity.", imageUrl: "./images/cultural_identity.png" },
        { word: "Global audience", type: "(n)", mean: "Khán giả toàn cầu", example: "K-pop has successfully reached a massive global audience.", imageUrl: "./images/global_audience.png" },
        { word: "Commercial success", type: "(n)", mean: "Thành công thương mại", example: "Despite critical backlash, the album was a huge commercial success.", imageUrl: "./images/commercial_success.png" }
    ],
    // Thêm đoạn này vào bên trong biến ieltsDatabase trong file vocab-data.js

    "personality": [
        { word: "Outgoing", type: "(adj)", mean: "Hướng ngoại", example: "She is very outgoing and enjoys meeting new people.", imageUrl: "./images/outgoing.png" },
        { word: "Sociable", type: "(adj)", mean: "Hòa đồng", example: "He is a sociable person who makes friends easily.", imageUrl: "./images/sociable.png" },
        { word: "Confident", type: "(adj)", mean: "Tự tin", example: "You need to be confident to speak in front of a crowd.", imageUrl: "./images/confident.png" },
        { word: "Optimistic", type: "(adj)", mean: "Lạc quan", example: "An optimistic person always sees the bright side of things.", imageUrl: "./images/optimistic.png" },
        { word: "Reliable", type: "(adj)", mean: "Đáng tin cậy", example: "She is very reliable and never misses a deadline.", imageUrl: "./images/reliable.png" },
        { word: "Responsible", type: "(adj)", mean: "Có trách nhiệm", example: "Parents are responsible for their children's safety.", imageUrl: "./images/responsible.png" },
        { word: "Hardworking", type: "(adj)", mean: "Chăm chỉ", example: "He is a hardworking student who always gets good grades.", imageUrl: "./images/hardworking.png" },
        { word: "Ambitious", type: "(adj)", mean: "Tham vọng", example: "She is ambitious and hopes to become a CEO one day.", imageUrl: "./images/ambitious.png" },
        { word: "Independent", type: "(adj)", mean: "Độc lập", example: "Moving away from home made him more independent.", imageUrl: "./images/independent.png" },
        { word: "Open-minded", type: "(adj)", mean: "Cởi mở", example: "It's important to be open-minded when traveling to new cultures.", imageUrl: "./images/open_minded.png" },
        { word: "Introverted", type: "(adj)", mean: "Hướng nội", example: "Introverted people often prefer quiet environments.", imageUrl: "./images/introverted.png" },
        { word: "Extroverted", type: "(adj)", mean: "Hướng ngoại", example: "Being extroverted helps him in his career as a salesperson.", imageUrl: "./images/extroverted.png" },
        { word: "Reserved", type: "(adj)", mean: "Kín đáo", example: "He is a bit reserved and doesn't talk much about himself.", imageUrl: "./images/reserved.png" },
        { word: "Sensitive", type: "(adj)", mean: "Nhạy cảm", example: "She is very sensitive to other people's feelings.", imageUrl: "./images/sensitive.png" },
        { word: "Straightforward", type: "(adj)", mean: "Thẳng thắn", example: "I like her because she is very straightforward and honest.", imageUrl: "./images/straightforward.png" },
        { word: "Perfectionist", type: "(n/adj)", mean: "Người cầu toàn", example: "As a perfectionist, she spends hours checking her work.", imageUrl: "./images/perfectionist.png" },
        { word: "Spontaneous", type: "(adj)", mean: "Bộc phát, tự nhiên", example: "Sometimes a spontaneous trip is more fun than a planned one.", imageUrl: "./images/spontaneous.png" },
        { word: "Curious", type: "(adj)", mean: "Tò mò", example: "The child was curious about how the machine worked.", imageUrl: "./images/curious.png" },
        { word: "Cautious", type: "(adj)", mean: "Thận trọng", example: "You should be cautious when driving in heavy rain.", imageUrl: "./images/cautious.png" },
        { word: "Flexible", type: "(adj)", mean: "Linh hoạt", example: "Workers need to be flexible to adapt to new changes.", imageUrl: "./images/flexible.png" },
        { word: "Selfish", type: "(adj)", mean: "Ích kỷ", example: "It was selfish of him to take all the food.", imageUrl: "./images/selfish.png" },
        { word: "Arrogant", type: "(adj)", mean: "Kiêu ngạo", example: "He is so arrogant that he thinks he is always right.", imageUrl: "./images/arrogant.png" },
        { word: "Stubborn", type: "(adj)", mean: "Bướng bỉnh", example: "She is too stubborn to admit she was wrong.", imageUrl: "./images/stubborn.png" },
        { word: "Lazy", type: "(adj)", mean: "Lười biếng", example: "He lost his job because he was lazy and unproductive.", imageUrl: "./images/lazy.png" },
        { word: "Impatient", type: "(adj)", mean: "Thiếu kiên nhẫn", example: "Don't be so impatient, the bus will be here soon.", imageUrl: "./images/impatient.png" },
        { word: "Irresponsible", type: "(adj)", mean: "Vô trách nhiệm", example: "It is irresponsible to leave a child alone at home.", imageUrl: "./images/irresponsible.png" },
        { word: "Moody", type: "(adj)", mean: "Thất thường", example: "Teenagers are often moody due to hormonal changes.", imageUrl: "./images/moody.png" },
        { word: "Jealous", type: "(adj)", mean: "Ghen tị", example: "He was jealous of his brother's success.", imageUrl: "./images/jealous.png" },
        { word: "Pessimistic", type: "(adj)", mean: "Bi quan", example: "A pessimistic outlook can make life very difficult.", imageUrl: "./images/pessimistic.png" },
        { word: "Narrow-minded", type: "(adj)", mean: "Bảo thủ", example: "His narrow-minded views prevented him from learning.", imageUrl: "./images/narrow_minded.png" }
    ],
    "weather": [
        { word: "Sunny", type: "(adj)", mean: "Có nắng", example: "We had a sunny day for our beach trip.", imageUrl: "./images/sunny.png" },
        { word: "Cloudy", type: "(adj)", mean: "Nhiều mây", example: "The sky is very cloudy, it might rain later.", imageUrl: "./images/cloudy.png" },
        { word: "Rainy", type: "(adj)", mean: "Có mưa", example: "September is often a rainy month in this city.", imageUrl: "./images/rainy.png" },
        { word: "Stormy", type: "(adj)", mean: "Có bão", example: "The ship stayed in the harbor during the stormy weather.", imageUrl: "./images/stormy.png" },
        { word: "Windy", type: "(adj)", mean: "Nhiều gió", example: "It's a windy day, great for flying a kite.", imageUrl: "./images/windy.png" },
        { word: "Humid", type: "(adj)", mean: "Ẩm ướt", example: "Tropical regions are often very hot and humid.", imageUrl: "./images/humid.png" },
        { word: "Dry", type: "(adj)", mean: "Khô ráo", example: "Cactus plants can survive in very dry climates.", imageUrl: "./images/dry.png" },
        { word: "Foggy", type: "(adj)", mean: "Có sương mù", example: "The driver slowed down because it was very foggy.", imageUrl: "./images/foggy.png" },
        { word: "Freezing", type: "(adj)", mean: "Rất lạnh", example: "The temperature tonight will be freezing.", imageUrl: "./images/freezing.png" },
        { word: "Scorching", type: "(adj)", mean: "Nóng gay gắt", example: "The sun was scorching during the afternoon.", imageUrl: "./images/scorching.png" },
        { word: "Climate", type: "(n)", mean: "Khí hậu", example: "The climate here is perfect for growing grapes.", imageUrl: "./images/climate.png" },
        { word: "Temperature", type: "(n)", mean: "Nhiệt độ", example: "The temperature has dropped significantly today.", imageUrl: "./images/temperature.png" },
        { word: "Heatwave", type: "(n)", mean: "Đợt nắng nóng", example: "Many elderly people suffer during a severe heatwave.", imageUrl: "./images/heatwave.png" },
        { word: "Cold spell", type: "(n)", mean: "Đợt lạnh", example: "A sudden cold spell destroyed the crops.", imageUrl: "./images/cold_spell.png" },
        { word: "Climate change", type: "(n)", mean: "Biến đổi khí hậu", example: "Climate change is a major threat to global biodiversity.", imageUrl: "./images/climate_change.png" },
        { word: "Global warming", type: "(n)", mean: "Nóng lên toàn cầu", example: "Global warming is causing sea levels to rise.", imageUrl: "./images/global_warming.png" },
        { word: "Tropical climate", type: "(n)", mean: "Khí hậu nhiệt đới", example: "Vietnam has a typical tropical climate.", imageUrl: "./images/tropical_climate.png" },
        { word: "Temperate climate", type: "(n)", mean: "Khí hậu ôn hòa", example: "Most of Europe enjoys a temperate climate.", imageUrl: "./images/temperate_climate.png" },
        { word: "Seasonal variation", type: "(n)", mean: "Sự thay đổi theo mùa", example: "There is little seasonal variation in the Amazon.", imageUrl: "./images/seasonal_variation.png" },
        { word: "Extreme weather", type: "(n)", mean: "Thời tiết cực đoan", example: "Extreme weather events are becoming more frequent.", imageUrl: "./images/extreme_weather.png" },
        { word: "Flood", type: "(n)", mean: "Lũ lụt", example: "The heavy rain caused a severe flood in the valley.", imageUrl: "./images/flood.png" },
        { word: "Drought", type: "(n)", mean: "Hạn hán", example: "The long drought led to a serious water shortage.", imageUrl: "./images/drought.png" },
        { word: "Hurricane", type: "(n)", mean: "Bão lớn", example: "The hurricane caused widespread damage to the coast.", imageUrl: "./images/hurricane.png" },
        { word: "Typhoon", type: "(n)", mean: "Bão (châu Á)", example: "A powerful typhoon is approaching the Philippines.", imageUrl: "./images/typhoon.png" },
        { word: "Thunderstorm", type: "(n)", mean: "Giông bão", example: "We could hear the thunderstorm from miles away.", imageUrl: "./images/thunderstorm.png" },
        { word: "Lightning", type: "(n)", mean: "Tia chớp", example: "Lightning struck the old oak tree last night.", imageUrl: "./images/lightning.png" },
        { word: "Weather forecast", type: "(n)", mean: "Dự báo thời tiết", example: "According to the weather forecast, it will snow tomorrow.", imageUrl: "./images/weather_forecast.png" },
        { word: "Rising sea levels", type: "(n)", mean: "Mực nước biển dâng", example: "Rising sea levels threaten many island nations.", imageUrl: "./images/rising_sea_levels.png" },
        { word: "Environmental impact", type: "(n)", mean: "Tác động môi trường", example: "Plastics have a negative environmental impact.", imageUrl: "./images/environmental_impact.png" },
        { word: "Natural disaster", type: "(n)", mean: "Thiên tai", example: "The earthquake was a terrible natural disaster.", imageUrl: "./images/natural_disaster.png" }
    ],
    "career": [
        { word: "Occupation", type: "(n)", mean: "Nghề nghiệp", example: "Please state your name, age, and occupation.", imageUrl: "./images/occupation.png" },
        { word: "Profession", type: "(n)", mean: "Nghề chuyên môn", example: "The medical profession requires years of study.", imageUrl: "./images/profession.png" },
        { word: "Career path", type: "(n)", mean: "Lộ trình nghề nghiệp", example: "Choosing the right career path is very important.", imageUrl: "./images/career_path.png" },
        { word: "Job satisfaction", type: "(n)", mean: "Sự hài lòng trong việc", example: "Higher pay does not always lead to job satisfaction.", imageUrl: "./images/job_satisfaction.png" },
        { word: "Workplace", type: "(n)", mean: "Nơi làm việc", example: "Diversity in the workplace leads to better ideas.", imageUrl: "./images/workplace.png" },
        { word: "Employee", type: "(n)", mean: "Nhân viên", example: "The company provides health insurance for every employee.", imageUrl: "./images/employee.png" },
        { word: "Employer", type: "(n)", mean: "Nhà tuyển dụng", example: "A good employer listens to the needs of the staff.", imageUrl: "./images/employer.png" },
        { word: "Colleague", type: "(n)", mean: "Đồng nghiệp", example: "I am going to lunch with my colleagues today.", imageUrl: "./images/colleague.png" },
        { word: "Full-time job", type: "(n)", mean: "Việc toàn thời gian", example: "She is looking for a full-time job after graduation.", imageUrl: "./images/full_time_job.png" },
        { word: "Part-time job", type: "(n)", mean: "Việc bán thời gian", example: "Working a part-time job can help students earn extra money.", imageUrl: "./images/part_time_job.png" },
        { word: "Professional skills", type: "(n)", mean: "Kỹ năng chuyên môn", example: "He is improving his professional skills through online courses.", imageUrl: "./images/professional_skills.png" },
        { word: "Soft skills", type: "(n)", mean: "Kỹ năng mềm", example: "Soft skills like communication are vital in management.", imageUrl: "./images/soft_skills.png" },
        { word: "Communication skills", type: "(n)", mean: "Kỹ năng giao tiếp", example: "Communication skills are key to resolving conflicts.", imageUrl: "./images/communication_skills.png" },
        { word: "Leadership skills", type: "(n)", mean: "Kỹ năng lãnh đạo", example: "She showed great leadership skills during the project.", imageUrl: "./images/leadership_skills.png" },
        { word: "Time management", type: "(n)", mean: "Quản lý thời gian", example: "Effective time management reduces stress at work.", imageUrl: "./images/time_management.png" },
        { word: "Problem-solving skills", type: "(n)", mean: "Kỹ năng giải quyết vđ", example: "Engineers need strong problem-solving skills.", imageUrl: "./images/problem_solving.png" },
        { word: "Career advancement", type: "(n)", mean: "Thăng tiến nghề nghiệp", example: "Performance reviews are important for career advancement.", imageUrl: "./images/career_advancement.png" },
        { word: "On-the-job training", type: "(n)", mean: "Đào tạo tại chỗ", example: "The company offers on-the-job training for new hires.", imageUrl: "./images/on_the_job_training.png" },
        { word: "Work experience", type: "(n)", mean: "Kinh nghiệm làm việc", example: "He has over ten years of work experience in finance.", imageUrl: "./images/work_experience.png" },
        { word: "Internship", type: "(n)", mean: "Thực tập", example: "Doing an internship is a good way to enter the industry.", imageUrl: "./images/internship.png" },
        { word: "Work-life balance", type: "(n)", mean: "Cân bằng cv-cs", example: "Flexible hours help maintain a good work-life balance.", imageUrl: "./images/work_life_balance.png" },
        { word: "Job security", type: "(n)", mean: "Sự ổn định công việc", example: "Government jobs often offer better job security.", imageUrl: "./images/job_security.png" },
        { word: "Unemployment", type: "(n)", mean: "Thất nghiệp", example: "The government is trying to reduce the unemployment rate.", imageUrl: "./images/unemployment.png" },
        { word: "Job opportunities", type: "(n)", mean: "Cơ hội việc làm", example: "This city offers many job opportunities for engineers.", imageUrl: "./images/job_opportunities.png" },
        { word: "Salary", type: "(n)", mean: "Mức lương", example: "He was happy with the starting salary they offered.", imageUrl: "./images/salary.png" },
        { word: "Promotion", type: "(n)", mean: "Thăng chức", example: "She got a promotion after working hard for two years.", imageUrl: "./images/promotion.png" },
        { word: "Resignation", type: "(n)", mean: "Sự từ chức", example: "The manager announced his resignation yesterday.", imageUrl: "./images/resignation.png" },
        { word: "Job burnout", type: "(n)", mean: "Kiệt sức vì cv", example: "Stress and long hours can lead to job burnout.", imageUrl: "./images/job_burnout.png" },
        { word: "Remote work", type: "(n)", mean: "Làm việc từ xa", example: "Technology has made remote work easier for many.", imageUrl: "./images/remote_work.png" },
        { word: "Freelancer", type: "(n)", mean: "Làm việc tự do", example: "Being a freelancer allows you to choose your own projects.", imageUrl: "./images/freelancer.png" }
    ],
    // Thêm đoạn code này vào tiếp trong ieltsDatabase ở file vocab-data.js

    "study_work": [
        { word: "Work-life balance", type: "(n)", mean: "Cân bằng công việc – cuộc sống", example: "It is difficult to maintain a good work-life balance when you have a lot of overtime.", imageUrl: "./images/work_life_balance.png" },
        { word: "Study-work balance", type: "(n)", mean: "Cân bằng học và làm", example: "Many students struggle with study-work balance during their part-time jobs.", imageUrl: "./images/study_work_balance.png" },
        { word: "Time management", type: "(n)", mean: "Quản lý thời gian", example: "Good time management is the key to finishing projects on time.", imageUrl: "./images/time_management.png" },
        { word: "Heavy workload", type: "(n)", mean: "Khối lượng công việc lớn", example: "A heavy workload can lead to a lot of stress for employees.", imageUrl: "./images/heavy_workload.png" },
        { word: "Academic pressure", type: "(n)", mean: "Áp lực học tập", example: "Students often face intense academic pressure during final exams.", imageUrl: "./images/academic_pressure.png" },
        { word: "Part-time job", type: "(n)", mean: "Công việc bán thời gian", example: "I have a part-time job at a local coffee shop.", imageUrl: "./images/part_time_job.png" },
        { word: "Full-time study", type: "(n)", mean: "Học toàn thời gian", example: "Full-time study requires a lot of dedication and focus.", imageUrl: "./images/full_time_study.png" },
        { word: "Flexible schedule", type: "(n)", mean: "Lịch trình linh hoạt", example: "Remote work often offers a more flexible schedule.", imageUrl: "./images/flexible_schedule.png" },
        { word: "Multitasking", type: "(n)", mean: "Làm nhiều việc cùng lúc", example: "Multitasking can sometimes reduce the quality of your work.", imageUrl: "./images/multitasking.png" },
        { word: "Prioritize tasks", type: "(v)", mean: "Ưu tiên công việc", example: "You should prioritize tasks that are urgent and important.", imageUrl: "./images/prioritize_tasks.png" },
        { word: "Transferable skills", type: "(n)", mean: "Kỹ năng có thể chuyển đổi", example: "Communication is one of the most important transferable skills.", imageUrl: "./images/transferable_skills.png" },
        { word: "Practical experience", type: "(n)", mean: "Kinh nghiệm thực tế", example: "Internships provide students with valuable practical experience.", imageUrl: "./images/practical_experience.png" },
        { word: "Theoretical knowledge", type: "(n)", mean: "Kiến thức lý thuyết", example: "Theoretical knowledge should be supported by practice.", imageUrl: "./images/theoretical_knowledge.png" },
        { word: "Skill development", type: "(n)", mean: "Phát triển kỹ năng", example: "The company invests a lot in the skill development of its staff.", imageUrl: "./images/skill_development.png" },
        { word: "Professional growth", type: "(n)", mean: "Phát triển nghề nghiệp", example: "Continuous learning is necessary for professional growth.", imageUrl: "./images/professional_growth.png" },
        { word: "Internship", type: "(n)", mean: "Thực tập", example: "He is doing a summer internship at a tech company.", imageUrl: "./images/internship.png" },
        { word: "On-the-job training", type: "(n)", mean: "Đào tạo tại nơi làm việc", example: "New employees receive on-the-job training from their seniors.", imageUrl: "./images/on_the_job_training.png" },
        { word: "Communication skills", type: "(n)", mean: "Kỹ năng giao tiếp", example: "Good communication skills help prevent misunderstandings.", imageUrl: "./images/communication_skills.png" },
        { word: "Problem-solving skills", type: "(n)", mean: "Kỹ năng giải quyết vấn đề", example: "Employers value people with strong problem-solving skills.", imageUrl: "./images/problem_solving.png" },
        { word: "Adaptability", type: "(n)", mean: "Khả năng thích nghi", example: "Adaptability is a vital quality in a changing work environment.", imageUrl: "./images/adaptability.png" },
        { word: "Burnout", type: "(n)", mean: "Kiệt sức", example: "Working long hours without breaks can lead to burnout.", imageUrl: "./images/burnout.png" },
        { word: "Fatigue", type: "(n)", mean: "Mệt mỏi", example: "Driver fatigue is a major cause of road accidents.", imageUrl: "./images/fatigue.png" },
        { word: "Stress management", type: "(n)", mean: "Quản lý căng thẳng", example: "Exercise is an effective method for stress management.", imageUrl: "./images/stress_management.png" },
        { word: "Financial independence", type: "(n)", mean: "Độc lập tài chính", example: "Having a job helps young people achieve financial independence.", imageUrl: "./images/financial_independence.png" },
        { word: "Earn a living", type: "(v)", mean: "Kiếm sống", example: "He works two jobs to earn a living for his family.", imageUrl: "./images/earn_a_living.png" },
        { word: "Job readiness", type: "(n)", mean: "Sự sẵn sàng cho công việc", example: "Vocational schools focus on increasing job readiness.", imageUrl: "./images/job_readiness.png" },
        { word: "Career prospects", type: "(n)", mean: "Triển vọng nghề nghiệp", example: "Graduating from a top university improves your career prospects.", imageUrl: "./images/career_prospects.png" },
        { word: "Academic performance", type: "(n)", mean: "Kết quả học tập", example: "His academic performance improved after he started tutoring.", imageUrl: "./images/academic_performance.png" },
        { word: "Dropout rate", type: "(n)", mean: "Tỷ lệ bỏ học", example: "The government is trying to reduce the high school dropout rate.", imageUrl: "./images/dropout_rate.png" },
        { word: "Long-term benefits", type: "(n)", mean: "Lợi ích lâu dài", example: "Saving money now will provide long-term benefits for your future.", imageUrl: "./images/long_term_benefits.png" }
    ],
    "crime_punishment": [
        { word: "Theft", type: "(n)", mean: "Trộm cắp", example: "Theft is a common problem in crowded tourist areas.", imageUrl: "./images/theft.png" },
        { word: "Robbery", type: "(n)", mean: "Cướp (có đe dọa/vũ lực)", example: "The bank was closed today after a violent robbery.", imageUrl: "./images/robbery.png" },
        { word: "Burglary", type: "(n)", mean: "Đột nhập trộm", example: "The family was on vacation when the burglary happened.", imageUrl: "./images/burglary.png" },
        { word: "Fraud", type: "(n)", mean: "Gian lận", example: "He was arrested for committing credit card fraud.", imageUrl: "./images/fraud.png" },
        { word: "Cybercrime", type: "(n)", mean: "Tội phạm mạng", example: "Cybercrime is increasing as more people shop online.", imageUrl: "./images/cybercrime.png" },
        { word: "Violent crime", type: "(n)", mean: "Tội phạm bạo lực", example: "The government is introducing new laws to reduce violent crime.", imageUrl: "./images/violent_crime.png" },
        { word: "Drug trafficking", type: "(n)", mean: "Buôn bán ma túy", example: "Drug trafficking is a serious global issue.", imageUrl: "./images/drug_trafficking.png" },
        { word: "Money laundering", type: "(n)", mean: "Rửa tiền", example: "The criminal used a fake business for money laundering.", imageUrl: "./images/money_laundering.png" },
        { word: "Shoplifting", type: "(n)", mean: "Ăn cắp trong cửa hàng", example: "He was caught shoplifting a bottle of perfume.", imageUrl: "./images/shoplifting.png" },
        { word: "Vandalism", type: "(n)", mean: "Phá hoại tài sản", example: "The park was closed due to acts of vandalism.", imageUrl: "./images/vandalism.png" },
        { word: "Law enforcement", type: "(n)", mean: "Cơ quan thực thi pháp luật", example: "Law enforcement agencies are working together to stop the gang.", imageUrl: "./images/law_enforcement.png" },
        { word: "Police officer", type: "(n)", mean: "Cảnh sát", example: "The police officer gave the driver a ticket for speeding.", imageUrl: "./images/police_officer.png" },
        { word: "Court trial", type: "(n)", mean: "Phiên tòa", example: "The court trial lasted for three weeks.", imageUrl: "./images/court_trial.png" },
        { word: "Judge", type: "(n)", mean: "Thẩm phán", example: "The judge will decide the final sentence.", imageUrl: "./images/judge.png" },
        { word: "Jury", type: "(n)", mean: "Bồi thẩm đoàn", example: "The jury found the defendant guilty of the crime.", imageUrl: "./images/jury.png" },
        { word: "Sentence", type: "(n/v)", mean: "Bản án / tuyên án", example: "The judge gave him a heavy sentence for his actions.", imageUrl: "./images/sentence.png" },
        { word: "Prison sentence", type: "(n)", mean: "Án tù", example: "He is serving a five-year prison sentence.", imageUrl: "./images/prison_sentence.png" },
        { word: "Life imprisonment", type: "(n)", mean: "Tù chung thân", example: "The killer was sentenced to life imprisonment.", imageUrl: "./images/life_imprisonment.png" },
        { word: "Capital punishment", type: "(n)", mean: "Án tử hình", example: "Many countries have abolished capital punishment.", imageUrl: "./images/capital_punishment.png" },
        { word: "Rehabilitation", type: "(n)", mean: "Cải tạo (phạm nhân)", example: "The prison focuses on the rehabilitation of young offenders.", imageUrl: "./images/rehabilitation.png" },
        { word: "Poverty", type: "(n)", mean: "Nghèo đói", example: "Poverty is often a major cause of high crime rates.", imageUrl: "./images/poverty.png" },
        { word: "Unemployment", type: "(n)", mean: "Thất nghiệp", example: "Unemployment can lead to social unrest and crime.", imageUrl: "./images/unemployment.png" },
        { word: "Social inequality", type: "(n)", mean: "Bất bình đẳng xã hội", example: "Social inequality often leads to division within a city.", imageUrl: "./images/social_inequality.png" },
        { word: "Peer pressure", type: "(n)", mean: "Áp lực bạn bè", example: "Teenagers may commit crimes due to peer pressure.", imageUrl: "./images/peer_pressure.png" },
        { word: "Crime prevention", type: "(n)", mean: "Phòng chống tội phạm", example: "Better street lighting can help in crime prevention.", imageUrl: "./images/crime_prevention.png" },
        { word: "Strict laws", type: "(n)", mean: "Luật nghiêm khắc", example: "Strict laws are needed to deter criminals.", imageUrl: "./images/strict_laws.png" },
        { word: "Deterrent", type: "(n)", mean: "Biện pháp răn đe", example: "High fines act as a deterrent for illegal parking.", imageUrl: "./images/deterrent.png" },
        { word: "Reoffending", type: "(n)", mean: "Tái phạm", example: "Support programs can help reduce the rate of reoffending.", imageUrl: "./images/reoffending.png" },
        { word: "Community service", type: "(n)", mean: "Lao động công ích", example: "He was ordered to do 100 hours of community service.", imageUrl: "./images/community_service.png" },
        { word: "Surveillance", type: "(n)", mean: "Giám sát", example: "The bank is under constant video surveillance.", imageUrl: "./images/surveillance.png" }
    ],
    "food_drinks": [
        { word: "Processed food", type: "(n)", mean: "Thực phẩm chế biến sẵn", example: "Eating too much processed food is bad for your health.", imageUrl: "./images/processed_food.png" },
        { word: "Junk food", type: "(n)", mean: "Đồ ăn nhanh/không lành mạnh", example: "Children should limit their intake of junk food.", imageUrl: "./images/junk_food.png" },
        { word: "Organic food", type: "(n)", mean: "Thực phẩm hữu cơ", example: "Organic food is grown without the use of chemical pesticides.", imageUrl: "./images/organic_food.png" },
        { word: "Home-cooked meal", type: "(n)", mean: "Bữa ăn nấu tại nhà", example: "Nothing is better than a fresh home-cooked meal.", imageUrl: "./images/home_cooked_meal.png" },
        { word: "Fast food", type: "(n)", mean: "Thức ăn nhanh", example: "Fast food is convenient but often contains high levels of salt.", imageUrl: "./images/fast_food.png" },
        { word: "Vegetarian diet", type: "(n)", mean: "Chế độ ăn chay", example: "She followed a strict vegetarian diet for health reasons.", imageUrl: "./images/vegetarian_diet.png" },
        { word: "Vegan diet", type: "(n)", mean: "Chế độ ăn thuần chay", example: "A vegan diet excludes all animal products, including eggs.", imageUrl: "./images/vegan_diet.png" },
        { word: "Balanced diet", type: "(n)", mean: "Chế độ ăn cân bằng", example: "A balanced diet includes fruits, vegetables, and protein.", imageUrl: "./images/balanced_diet.png" },
        { word: "Street food", type: "(n)", mean: "Đồ ăn đường phố", example: "Vietnam is famous for its delicious and cheap street food.", imageUrl: "./images/street_food.png" },
        { word: "Traditional cuisine", type: "(n)", mean: "Ẩm thực truyền thống", example: "I love exploring the traditional cuisine of different countries.", imageUrl: "./images/traditional_cuisine.png" },
        { word: "Delicious", type: "(adj)", mean: "Ngon", example: "This chocolate cake is absolutely delicious.", imageUrl: "./images/delicious.png" },
        { word: "Flavorful", type: "(adj)", mean: "Đậm đà", example: "The soup was very flavorful due to the fresh herbs.", imageUrl: "./images/flavorful.png" },
        { word: "Savory", type: "(adj)", mean: "Mặn (không ngọt)", example: "I prefer savory snacks over sweet ones.", imageUrl: "./images/savory.png" },
        { word: "Spicy", type: "(adj)", mean: "Cay", example: "Thai food is known for being very spicy.", imageUrl: "./images/spicy.png" },
        { word: "Bitter", type: "(adj)", mean: "Đắng", example: "Dark chocolate has a slightly bitter taste.", imageUrl: "./images/bitter.png" },
        { word: "Sweet", type: "(adj)", mean: "Ngọt", example: "The fruit was very ripe and sweet.", imageUrl: "./images/sweet.png" },
        { word: "Sour", type: "(adj)", mean: "Chua", example: "Lemons have a very sour flavor.", imageUrl: "./images/sour.png" },
        { word: "Cook from scratch", type: "(v)", mean: "Nấu từ đầu (nguyên liệu tươi)", example: "My grandmother always used to cook everything from scratch.", imageUrl: "./images/cook_from_scratch.png" },
        { word: "Grilled", type: "(adj)", mean: "Nướng", example: "I would like the grilled fish with a side salad.", imageUrl: "./images/grilled.png" },
        { word: "Steamed", type: "(adj)", mean: "Hấp", example: "Steamed vegetables are a healthy addition to any meal.", imageUrl: "./images/steamed.png" },
        { word: "Soft drinks", type: "(n)", mean: "Nước ngọt", example: "Soft drinks often contain high amounts of sugar.", imageUrl: "./images/soft_drinks.png" },
        { word: "Alcoholic beverages", type: "(n)", mean: "Đồ uống có cồn", example: "Selling alcoholic beverages to minors is illegal.", imageUrl: "./images/alcoholic_beverages.png" },
        { word: "Fresh juice", type: "(n)", mean: "Nước ép tươi", example: "Fresh juice is a great way to start your morning.", imageUrl: "./images/fresh_juice.png" },
        { word: "Caffeine intake", type: "(n)", mean: "Lượng caffeine tiêu thụ", example: "High caffeine intake can make it difficult to sleep.", imageUrl: "./images/caffeine_intake.png" },
        { word: "Hydration", type: "(n)", mean: "Sự cung cấp đủ nước", example: "Drinking water is essential for proper hydration.", imageUrl: "./images/hydration.png" },
        { word: "Nutritional value", type: "(n)", mean: "Giá trị dinh dưỡng", example: "The nutritional value of fast food is usually very low.", imageUrl: "./images/nutritional_value.png" },
        { word: "Calorie intake", type: "(n)", mean: "Lượng calo nạp vào", example: "You should monitor your daily calorie intake to lose weight.", imageUrl: "./images/calorie_intake.png" },
        { word: "Food safety", type: "(n)", mean: "An toàn thực phẩm", example: "Food safety is a top priority for any restaurant.", imageUrl: "./images/food_safety.png" },
        { word: "Eating habits", type: "(n)", mean: "Thói quen ăn uống", example: "Good eating habits are formed during childhood.", imageUrl: "./images/eating_habits.png" },
        { word: "Dietary preference", type: "(n)", mean: "Sở thích ăn uống", example: "Please let us know if you have any specific dietary preferences.", imageUrl: "./images/dietary_preference.png" }
    ],
    // Thêm đoạn này vào tiếp trong ieltsDatabase ở file vocab-data.js

    "fruit": [
        { word: "Citrus fruits", type: "(n)", mean: "Trái cây họ cam quýt", example: "Citrus fruits like oranges and lemons are high in Vitamin C.", imageUrl: "./images/citrus_fruits.png" },
        { word: "Tropical fruits", type: "(n)", mean: "Trái cây nhiệt đới", example: "Mangoes and pineapples are popular tropical fruits in Vietnam.", imageUrl: "./images/tropical_fruits.png" },
        { word: "Berries", type: "(n)", mean: "Quả mọng", example: "Strawberries and blueberries are delicious berries used in desserts.", imageUrl: "./images/berries.png" },
        { word: "Stone fruits", type: "(n)", mean: "Trái cây có hạt cứng", example: "Peaches and plums are common examples of stone fruits.", imageUrl: "./images/stone_fruits.png" },
        { word: "Exotic fruits", type: "(n)", mean: "Trái cây ngoại lai", example: "Dragon fruit was once considered an exotic fruit in Western countries.", imageUrl: "./images/exotic_fruits.png" },
        { word: "Seasonal fruits", type: "(n)", mean: "Trái cây theo mùa", example: "Buying seasonal fruits is usually cheaper and fresher.", imageUrl: "./images/seasonal_fruits.png" },
        { word: "Fresh produce", type: "(n)", mean: "Nông sản tươi", example: "The local market is the best place to find fresh produce.", imageUrl: "./images/fresh_produce.png" },
        { word: "Organic fruits", type: "(n)", mean: "Trái cây hữu cơ", example: "Organic fruits are grown without using chemical pesticides.", imageUrl: "./images/organic_fruits.png" },
        { word: "Ripe fruit", type: "(n)", mean: "Trái chín", example: "You should wait for the banana to become a ripe fruit before eating.", imageUrl: "./images/ripe_fruit.png" },
        { word: "Unripe fruit", type: "(n)", mean: "Trái chưa chín", example: "Unripe fruit often has a sour or bitter taste.", imageUrl: "./images/unripe_fruit.png" },
        { word: "Juicy", type: "(adj)", mean: "Mọng nước", example: "The watermelon was very sweet and juicy.", imageUrl: "./images/juicy.png" },
        { word: "Sweet", type: "(adj)", mean: "Ngọt", example: "I prefer sweet apples over sour ones.", imageUrl: "./images/sweet.png" },
        { word: "Sour", type: "(adj)", mean: "Chua", example: "Lemons have a very strong sour flavor.", imageUrl: "./images/sour.png" },
        { word: "Tangy", type: "(adj)", mean: "Chua nhẹ", example: "This yogurt has a tangy taste that is very refreshing.", imageUrl: "./images/tangy.png" },
        { word: "Bitter", type: "(adj)", mean: "Đắng", example: "The skin of some fruits can be quite bitter.", imageUrl: "./images/bitter.png" },
        { word: "Refreshing", type: "(adj)", mean: "Thanh mát", example: "A cold slice of melon is very refreshing on a hot day.", imageUrl: "./images/refreshing.png" },
        { word: "Aromatic", type: "(adj)", mean: "Thơm", example: "The durian is known for its strong aromatic smell.", imageUrl: "./images/aromatic.png" },
        { word: "Fibrous", type: "(adj)", mean: "Nhiều xơ", example: "Pineapples can be quite fibrous if they are not ripe.", imageUrl: "./images/fibrous.png" },
        { word: "Seedless", type: "(adj)", mean: "Không hạt", example: "Seedless grapes are much easier to eat as a snack.", imageUrl: "./images/seedless.png" },
        { word: "Nutrient-rich", type: "(adj)", mean: "Giàu dinh dưỡng", example: "Avocados are nutrient-rich and contain healthy fats.", imageUrl: "./images/nutrient_rich.png" },
        { word: "Vitamin intake", type: "(n)", mean: "Lượng vitamin hấp thụ", example: "Eating fruit daily helps increase your vitamin intake.", imageUrl: "./images/vitamin_intake.png" },
        { word: "Dietary fiber", type: "(n)", mean: "Chất xơ", example: "Apples provide a good source of dietary fiber for digestion.", imageUrl: "./images/dietary_fiber.png" },
        { word: "Immune-boosting", type: "(adj)", mean: "Tăng cường miễn dịch", example: "Many fruits have immune-boosting properties to fight illnesses.", imageUrl: "./images/immune_boosting.png" },
        { word: "Antioxidants", type: "(n)", mean: "Chất chống oxy hóa", example: "Blueberries are famous for being high in antioxidants.", imageUrl: "./images/antioxidants.png" },
        { word: "Natural sugar", type: "(n)", mean: "Đường tự nhiên", example: "Fruits contain natural sugar, which is healthier than refined sugar.", imageUrl: "./images/natural_sugar.png" },
        { word: "Calorie content", type: "(n)", mean: "Hàm lượng calo", example: "Strawberries have a very low calorie content.", imageUrl: "./images/calorie_content.png" },
        { word: "Balanced diet", type: "(n)", mean: "Chế độ ăn cân bằng", example: "A balanced diet must include a variety of fruits and vegetables.", imageUrl: "./images/balanced_diet_fruit.png" },
        { word: "Fruit consumption", type: "(n)", mean: "Việc tiêu thụ trái cây", example: "Doctors recommend increasing fruit consumption for better health.", imageUrl: "./images/fruit_consumption.png" },
        { word: "Food preservation", type: "(n)", mean: "Bảo quản thực phẩm", example: "Drying is an ancient method of fruit food preservation.", imageUrl: "./images/food_preservation.png" },
        { word: "Processed fruit products", type: "(n)", mean: "Sản phẩm trái cây chế biến", example: "Jam and dried fruits are common processed fruit products.", imageUrl: "./images/processed_fruit_products.png" }
    ],
    "transportation": [
        { word: "Public transport", type: "(n)", mean: "Phương tiện công cộng", example: "Many people use public transport to save money on fuel.", imageUrl: "./images/public_transport.png" },
        { word: "Private vehicle", type: "(n)", mean: "Phương tiện cá nhân", example: "Owning a private vehicle provides more flexibility for traveling.", imageUrl: "./images/private_vehicle.png" },
        { word: "Mass transit", type: "(n)", mean: "Vận tải công cộng lớn", example: "The city needs an efficient mass transit system to reduce traffic.", imageUrl: "./images/mass_transit.png" },
        { word: "Commuter train", type: "(n)", mean: "Tàu cho người đi làm", example: "The commuter train is usually crowded during rush hour.", imageUrl: "./images/commuter_train.png" },
        { word: "Subway/Metro", type: "(n)", mean: "Tàu điện ngầm", example: "The subway is the fastest way to get around London.", imageUrl: "./images/subway.png" },
        { word: "Bus rapid transit (BRT)", type: "(n)", mean: "Hệ thống xe buýt nhanh", example: "BRT systems help buses avoid traffic jams by using special lanes.", imageUrl: "./images/brt.png" },
        { word: "Ride-sharing", type: "(n)", mean: "Đi chung xe", example: "Apps like Grab and Uber have made ride-sharing very popular.", imageUrl: "./images/ride_sharing.png" },
        { word: "Electric vehicle (EV)", type: "(n)", mean: "Xe điện", example: "Electric vehicles are better for the environment than gas cars.", imageUrl: "./images/ev.png" },
        { word: "Bicycle", type: "(n)", mean: "Xe đạp", example: "Using a bicycle is a healthy and green way to commute.", imageUrl: "./images/bicycle.png" },
        { word: "High-speed rail", type: "(n)", mean: "Tàu cao tốc", example: "High-speed rail connects major cities in a very short time.", imageUrl: "./images/high_speed_rail.png" },
        { word: "Traffic congestion", type: "(n)", mean: "Tắc nghẽn giao thông", example: "Traffic congestion is a serious problem in big cities like Hanoi.", imageUrl: "./images/traffic_congestion.png" },
        { word: "Road infrastructure", type: "(n)", mean: "Cơ sở hạ tầng đường bộ", example: "The government is investing in road infrastructure for better safety.", imageUrl: "./images/road_infrastructure.png" },
        { word: "Rush hour", type: "(n)", mean: "Giờ cao điểm", example: "I try to avoid driving during the morning rush hour.", imageUrl: "./images/rush_hour.png" },
        { word: "Traffic flow", type: "(n)", mean: "Lưu lượng giao thông", example: "New traffic lights were installed to improve the traffic flow.", imageUrl: "./images/traffic_flow.png" },
        { word: "Road safety", type: "(n)", mean: "An toàn giao thông", example: "Road safety campaigns help reduce the number of accidents.", imageUrl: "./images/road_safety.png" },
        { word: "Traffic jam", type: "(n)", mean: "Kẹt xe", example: "We were stuck in a traffic jam for over an hour.", imageUrl: "./images/traffic_jam.png" },
        { word: "Pedestrian crossing", type: "(n)", mean: "Vạch qua đường", example: "Drivers must stop for people at the pedestrian crossing.", imageUrl: "./images/pedestrian_crossing.png" },
        { word: "Cycle lane", type: "(n)", mean: "Làn đường cho xe đạp", example: "Cycle lanes make it safer for people to bike to work.", imageUrl: "./images/cycle_lane.png" },
        { word: "Parking space", type: "(n)", mean: "Chỗ đỗ xe", example: "Finding a parking space in the city center is very difficult.", imageUrl: "./images/parking_space.png" },
        { word: "Urban planning", type: "(n)", mean: "Quy hoạch đô thị", example: "Good urban planning includes efficient transport systems.", imageUrl: "./images/urban_planning.png" },
        { word: "Carbon emissions", type: "(n)", mean: "Khí thải carbon", example: "Transport is a major source of carbon emissions in cities.", imageUrl: "./images/carbon_emissions_transport.png" },
        { word: "Air pollution", type: "(n)", mean: "Ô nhiễm không khí", example: "Vehicle exhaust is the primary cause of air pollution.", imageUrl: "./images/air_pollution_transport.png" },
        { word: "Sustainable transport", type: "(n)", mean: "Giao thông bền vững", example: "Walking and cycling are forms of sustainable transport.", imageUrl: "./images/sustainable_transport.png" },
        { word: "Fuel-efficient", type: "(adj)", mean: "Tiết kiệm nhiên liệu", example: "He bought a fuel-efficient car to lower his expenses.", imageUrl: "./images/fuel_efficient.png" },
        { word: "Environmentally friendly", type: "(adj)", mean: "Thân thiện môi trường", example: "Public transport is more environmentally friendly than private cars.", imageUrl: "./images/environmentally_friendly.png" },
        { word: "Traffic regulations", type: "(n)", mean: "Luật giao thông", example: "Everyone should follow traffic regulations to stay safe.", imageUrl: "./images/traffic_regulations.png" },
        { word: "Public awareness", type: "(n)", mean: "Nhận thức cộng đồng", example: "Public awareness about road safety is still quite low.", imageUrl: "./images/public_awareness.png" },
        { word: "Infrastructure development", type: "(n)", mean: "Phát triển hạ tầng", example: "Infrastructure development is key to economic growth.", imageUrl: "./images/infrastructure_development.png" },
        { word: "Reduce congestion", type: "(v)", mean: "Giảm tắc nghẽn", example: "Expanding the metro system will help reduce congestion.", imageUrl: "./images/reduce_congestion.png" },
        { word: "Alternative transport", type: "(n)", mean: "Phương tiện thay thế", example: "Scooters are a popular alternative transport in small towns.", imageUrl: "./images/alternative_transport.png" }
    ]
};
    