// vocab-data.js - TỔNG KHO DỮ LIỆU
const ieltsDatabase = {
    "travel": [
        { word: "Destination", type: "Noun", mean: "Điểm đến", example: "After ten hours of driving, we finally reached our destination.", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=400" },
        { word: "Itinerary", type: "Noun", mean: "Lịch trình", example: "We have a very tight itinerary for our three-day trip to Hanoi.", imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=400" },
        { word: "Accommodation", type: "Noun", mean: "Chỗ ở", example: "Hotel accommodation is included in the price of the tour.", imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=400" }
    ],
    "education": [
        { word: "Curriculum", type: "(n)", mean: "Chương trình học", example: "The school curriculum includes a wide range of subjects.", imageUrl: "./images/curriculum.jpg" },
        { word: "Syllabus", type: "(n)", mean: "Đề cương môn học", example: "Please refer to the syllabus for the exam dates.", imageUrl: "./images/syllabus.jpg" },
        { word: "Discipline", type: "(n)", mean: "Ngành học / kỷ luật", example: "Engineering is a challenging discipline.", imageUrl: "./images/discipline.png" },
        { word: "Pedagogy", type: "(n)", mean: "Phương pháp giảng dạy", example: "Modern pedagogy focuses on student engagement.", imageUrl: "./images/pedagogy.jpg" },
        { word: "Assessment", type: "(n)", mean: "Đánh giá", example: "Continuous assessment helps track student progress.", imageUrl: "./images/assessment.png" },
        { word: "Qualification", type: "(n)", mean: "Bằng cấp", example: "He has the right qualifications for the job.", imageUrl: "./images/qualification.jpg" },
        { word: "Academic performance", type: "(n)", mean: "Thành tích học tập", example: "His academic performance improved significantly.", imageUrl: "./images/academic_performance.png" },
        { word: "Compulsory", type: "(adj)", mean: "Bắt buộc", example: "Math and English are compulsory subjects.", imageUrl: "./images/compulsory.jpg" },
        { word: "Optional", type: "(adj)", mean: "Tự chọn", example: "Students can choose from several optional modules.", imageUrl: "./images/optional.jpg" },
        { word: "Extracurricular", type: "(adj)", mean: "Ngoại khóa", example: "Extracurricular activities help build soft skills.", imageUrl: "./images/extracurricular.jpg" },
        { word: "Self-directed learning", type: "(n)", mean: "Tự học", example: "Self-directed learning is key to success in university.", imageUrl: "./images/self_directed_learning.jpg" },
        { word: "Rote learning", type: "(n)", mean: "Học vẹt", example: "Rote learning is not as effective as understanding concepts.", imageUrl: "./images/rote_learning.png" },
        { word: "Critical thinking", type: "(n)", mean: "Tư duy phản biện", example: "University education encourages critical thinking.", imageUrl: "./images/critical_thinking.jpg" },
        { word: "Analytical skills", type: "(n)", mean: "Kỹ năng phân tích", example: "Engineers need strong analytical skills to solve problems.", imageUrl: "./images/analytical_skills.jpg" },
        { word: "Collaborative learning", type: "(n)", mean: "Học nhóm", example: "Collaborative learning allows students to share ideas.", imageUrl: "./images/collaborative_learning.jpg" },
        { word: "Student-centered approach", type: "(n)", mean: "Lấy học sinh làm trung tâm", example: "The teacher adopted a student-centered approach.", imageUrl: "./images/student_centered.jpg" },
        { word: "Theoretical knowledge", type: "(n)", mean: "Lý thuyết", example: "Theoretical knowledge should be combined with practice.", imageUrl: "./images/theoretical_knowledge.jpg" },
        { word: "Practical skills", type: "(n)", mean: "Kỹ năng thực hành", example: "Lab work is important for developing practical skills.", imageUrl: "./images/practical_skills.jpg" },
        { word: "Cognitive development", type: "(n)", mean: "Phát triển nhận thức", example: "Play is vital for a child's cognitive development.", imageUrl: "./images/cognitive_development.jpg" },
        { word: "Knowledge retention", type: "(n)", mean: "Khả năng ghi nhớ", example: "Active learning improves knowledge retention.", imageUrl: "./images/knowledge_retention.jpg" },
        { word: "Higher education", type: "(n)", mean: "Giáo dục đại học", example: "Higher education opens many career opportunities.", imageUrl: "./images/higher_education.png" },
        { word: "Vocational training", type: "(n)", mean: "Đào tạo nghề", example: "Vocational training focuses on specific job skills.", imageUrl: "./images/vocational_training.jpg" },
        { word: "Distance learning", type: "(n)", mean: "Học từ xa", example: "Distance learning is flexible for working students.", imageUrl: "./images/distance_learning.jpg" },
        { word: "Online learning", type: "(n)", mean: "Học trực tuyến", example: "Many universities now offer online platforms.", imageUrl: "./images/online_learning.jpg" },
        { word: "Educational inequality", type: "(n)", mean: "Bất bình đẳng giáo dục", example: "Governments should reduce educational inequality.", imageUrl: "./images/educational_inequality.jpg" },
        { word: "Tuition fees", type: "(n)", mean: "Học phí", example: "High tuition fees can be a barrier to entry.", imageUrl: "./images/tuition_fees.jpg" },
        { word: "Dropout rate", type: "(n)", mean: "Tỷ lệ bỏ học", example: "The university is trying to lower its dropout rate.", imageUrl: "./images/dropout_rate.jpg" },
        { word: "Literacy rate", type: "(n)", mean: "Tỷ lệ biết chữ", example: "The country's literacy rate has increased.", imageUrl: "./images/literacy_rate.jpg" },
        { word: "Academic pressure", type: "(n)", mean: "Áp lực học tập", example: "Students often face intense pressure during finals.", imageUrl: "./images/academic_pressure.jpg" },
        { word: "Holistic education", type: "(n)", mean: "Giáo dục toàn diện", example: "Holistic education develops both mind and character.", imageUrl: "./images/holistic_education.jpg" }
    ],
    "environment": [
        { word: "Climate change", type: "(n)", mean: "Biến đổi khí hậu", example: "Climate change is one of the most pressing global issues today.", imageUrl: "./images/climate_change.png" },
        { word: "Global warming", type: "(n)", mean: "Nóng lên toàn cầu", example: "Global warming is causing polar ice caps to melt at an alarming rate.", imageUrl: "./images/global_warming.png" },
        { word: "Air pollution", type: "(n)", mean: "Ô nhiễm không khí", example: "Strict regulations are needed to reduce air pollution in major cities.", imageUrl: "./images/air_pollution.png" },
        { word: "Water contamination", type: "(n)", mean: "Ô nhiễm nguồn nước", example: "Water contamination from factories poses a severe threat to marine life.", imageUrl: "./images/water_contamination.png" },
        { word: "Deforestation", type: "(n)", mean: "Nạn phá rừng", example: "Deforestation leads to soil erosion and loss of animal habitats.", imageUrl: "./images/deforestation.png" },
        { word: "Biodiversity loss", type: "(n)", mean: "Suy giảm đa dạng sinh học", example: "The destruction of the rainforest contributes significantly to biodiversity loss.", imageUrl: "./images/biodiversity_loss.png" },
        { word: "Habitat destruction", type: "(n)", mean: "Phá hủy môi trường sống", example: "Many species are endangered due to habitat destruction.", imageUrl: "./images/habitat_destruction.png" },
        { word: "Overpopulation", type: "(n)", mean: "Bùng nổ dân số", example: "Overpopulation puts immense pressure on natural resources and infrastructure.", imageUrl: "./images/overpopulation.png" },
        { word: "Waste accumulation", type: "(n)", mean: "Sự tích tụ rác thải", example: "Waste accumulation in landfills is a major environmental concern.", imageUrl: "./images/waste_accumulation.png" },
        { word: "Resource depletion", type: "(n)", mean: "Cạn kiệt tài nguyên", example: "The continuous reliance on fossil fuels accelerates resource depletion.", imageUrl: "./images/resource_depletion.png" },
        { word: "Renewable energy", type: "(n)", mean: "Năng lượng tái tạo", example: "Governments should invest more heavily in renewable energy sources like wind and solar.", imageUrl: "./images/renewable_energy.png" },
        { word: "Sustainable development", type: "(n)", mean: "Phát triển bền vững", example: "Sustainable development ensures economic growth without harming the environment.", imageUrl: "./images/sustainable_development.png" },
        { word: "Carbon footprint", type: "(n)", mean: "Lượng khí thải carbon", example: "Using public transport is an effective way to reduce your carbon footprint.", imageUrl: "./images/carbon_footprint.png" },
        { word: "Recycling", type: "(n)", mean: "Tái chế", example: "Promoting a culture of recycling can significantly reduce household waste.", imageUrl: "./images/recycling.png" },
        { word: "Waste management", type: "(n)", mean: "Quản lý rác thải", example: "Effective waste management systems are vital for rapidly growing urban areas.", imageUrl: "./images/waste_management.png" },
        { word: "Energy conservation", type: "(n)", mean: "Tiết kiệm năng lượng", example: "Energy conservation measures can lower electricity bills and protect nature.", imageUrl: "./images/energy_conservation.png" },
        { word: "Eco-friendly", type: "(adj)", mean: "Thân thiện với môi trường", example: "Many consumers now prefer to buy eco-friendly products to reduce waste.", imageUrl: "./images/eco_friendly.png" },
        { word: "Green technology", type: "(n)", mean: "Công nghệ xanh", example: "Advances in green technology are essential for combating climate change.", imageUrl: "./images/green_technology.png" },
        { word: "Environmental protection", type: "(n)", mean: "Bảo vệ môi trường", example: "Environmental protection should be prioritized over short-term economic gains.", imageUrl: "./images/environmental_protection.png" },
        { word: "Conservation", type: "(n)", mean: "Bảo tồn", example: "Wildlife conservation programs help protect endangered species from extinction.", imageUrl: "./images/conservation.png" },
        { word: "Industrial emissions", type: "(n)", mean: "Khí thải công nghiệp", example: "Factories must install filters to reduce harmful industrial emissions.", imageUrl: "./images/industrial_emissions.png" },
        { word: "Fossil fuels", type: "(n)", mean: "Nhiên liệu hóa thạch", example: "Burning fossil fuels is the primary driver of the greenhouse effect.", imageUrl: "./images/fossil_fuels.png" },
        { word: "Urbanization", type: "(n)", mean: "Đô thị hóa", example: "Rapid urbanization has led to the loss of agricultural land around the city.", imageUrl: "./images/urbanization.png" },
        { word: "Agricultural runoff", type: "(n)", mean: "Nước thải nông nghiệp", example: "Agricultural runoff containing pesticides can severely pollute local rivers.", imageUrl: "./images/agricultural_runoff.png" },
        { word: "Illegal logging", type: "(n)", mean: "Khai thác gỗ trái phép", example: "Strict penalties must be enforced to stop illegal logging in national parks.", imageUrl: "./images/illegal_logging.png" },
        { word: "Overconsumption", type: "(n)", mean: "Tiêu thụ quá mức", example: "Our culture of overconsumption is rapidly depleting the Earth's natural resources.", imageUrl: "./images/overconsumption.png" },
        { word: "Plastic waste", type: "(n)", mean: "Rác thải nhựa", example: "Marine life is severely threatened by the sheer volume of plastic waste in the oceans.", imageUrl: "./images/plastic_waste.png" },
        { word: "Greenhouse gases", type: "(n)", mean: "Khí nhà kính", example: "Carbon dioxide and methane are the most prominent greenhouse gases.", imageUrl: "./images/greenhouse_gases.png" },
        { word: "Land degradation", type: "(n)", mean: "Thoái hóa đất", example: "Intensive farming practices often lead to severe land degradation over time.", imageUrl: "./images/land_degradation.png" },
        { word: "Toxic waste", type: "(n)", mean: "Chất thải độc hại", example: "Safe disposal of toxic waste is required by strict environmental laws.", imageUrl: "./images/toxic_waste.png" }
    ],
    "health": [
        { word: "Balanced diet", type: "(n)", mean: "Chế độ ăn cân bằng", example: "Maintaining a balanced diet is crucial for a healthy lifestyle.", imageUrl: "./images/balanced_diet.png" },
        { word: "Nutrient-rich", type: "(adj)", mean: "Giàu dinh dưỡng", example: "You should include more nutrient-rich foods like spinach in your meals.", imageUrl: "./images/nutrient_rich.png" },
        { word: "Well-being", type: "(n)", mean: "Sức khỏe tổng thể", example: "Yoga and meditation can significantly improve your overall well-being.", imageUrl: "./images/well_being.png" },
        { word: "Physical fitness", type: "(n)", mean: "Thể lực", example: "Regular training is required to achieve a high level of physical fitness.", imageUrl: "./images/physical_fitness.png" },
        { word: "Regular exercise", type: "(n)", mean: "Tập thể dục đều đặn", example: "Regular exercise helps to reduce the risk of heart disease.", imageUrl: "./images/regular_exercise.png" },
        { word: "Healthy habits", type: "(n)", mean: "Thói quen lành mạnh", example: "Developing healthy habits early in life can prevent future illnesses.", imageUrl: "./images/healthy_habits.png" },
        { word: "Lifestyle choices", type: "(n)", mean: "Lựa chọn lối sống", example: "Our daily lifestyle choices have a direct impact on our lifespan.", imageUrl: "./images/lifestyle_choices.png" },
        { word: "Preventive healthcare", type: "(n)", mean: "Chăm sóc sức khỏe phòng ngừa", example: "Preventive healthcare focuses on preventing diseases rather than treating them.", imageUrl: "./images/preventive_healthcare.png" },
        { word: "Immune system", type: "(n)", mean: "Hệ miễn dịch", example: "Eating plenty of fruits and vegetables strengthens the immune system.", imageUrl: "./images/immune_system.png" },
        { word: "Mental health", type: "(n)", mean: "Sức khỏe tinh thần", example: "Mental health is just as important as physical health.", imageUrl: "./images/mental_health.png" },
        { word: "Calorie intake", type: "(n)", mean: "Lượng calo nạp vào", example: "People trying to lose weight need to monitor their daily calorie intake.", imageUrl: "./images/calorie_intake.png" },
        { word: "Processed food", type: "(n)", mean: "Thực phẩm chế biến sẵn", example: "Consuming too much processed food can lead to serious health problems.", imageUrl: "./images/processed_food.png" },
        { word: "Junk food", type: "(n)", mean: "Đồ ăn nhanh", example: "Parents should limit the amount of junk food their children eat.", imageUrl: "./images/junk_food.png" },
        { word: "Sugar consumption", type: "(n)", mean: "Lượng tiêu thụ đường", example: "High sugar consumption is strongly linked to type 2 diabetes.", imageUrl: "./images/sugar_consumption.png" },
        { word: "Organic food", type: "(n)", mean: "Thực phẩm hữu cơ", example: "Many people prefer organic food because it is free from pesticides.", imageUrl: "./images/organic_food.png" },
        { word: "Dietary fiber", type: "(n)", mean: "Chất xơ", example: "Foods rich in dietary fiber are good for your digestive system.", imageUrl: "./images/dietary_fiber.png" },
        { word: "Vitamin deficiency", type: "(n)", mean: "Thiếu vitamin", example: "Vitamin deficiency can cause various health issues like fatigue.", imageUrl: "./images/vitamin_deficiency.png" },
        { word: "Malnutrition", type: "(n)", mean: "Suy dinh dưỡng", example: "Malnutrition remains a serious problem in many developing countries.", imageUrl: "./images/malnutrition.png" },
        { word: "Hydration", type: "(n)", mean: "Sự cung cấp đủ nước", example: "Proper hydration is essential, especially after a heavy workout.", imageUrl: "./images/hydration.png" },
        { word: "Portion control", type: "(n)", mean: "Kiểm soát khẩu phần ăn", example: "Portion control is an effective strategy for weight management.", imageUrl: "./images/portion_control.png" },
        { word: "Obesity", type: "(n)", mean: "Béo phì", example: "Childhood obesity has become a major public health concern globally.", imageUrl: "./images/obesity.png" },
        { word: "Sedentary lifestyle", type: "(n)", mean: "Lối sống ít vận động", example: "A sedentary lifestyle is a major risk factor for cardiovascular diseases.", imageUrl: "./images/sedentary_lifestyle.png" },
        { word: "Chronic disease", type: "(n)", mean: "Bệnh mãn tính", example: "Smoking significantly increases the risk of developing a chronic disease.", imageUrl: "./images/chronic_disease.png" },
        { word: "Cardiovascular disease", type: "(n)", mean: "Bệnh tim mạch", example: "Cardiovascular disease is one of the leading causes of death worldwide.", imageUrl: "./images/cardiovascular_disease.png" },
        { word: "Stress management", type: "(n)", mean: "Quản lý căng thẳng", example: "Effective stress management techniques include deep breathing and meditation.", imageUrl: "./images/stress_management.png" },
        { word: "Sleep deprivation", type: "(n)", mean: "Thiếu ngủ", example: "Chronic sleep deprivation can negatively affect your concentration and mood.", imageUrl: "./images/sleep_deprivation.png" },
        { word: "Addiction", type: "(n)", mean: "Nghiện", example: "Smartphone addiction is becoming increasingly common among teenagers.", imageUrl: "./images/addiction.png" },
        { word: "Public health", type: "(n)", mean: "Y tế cộng đồng", example: "The government needs to invest more money in public health campaigns.", imageUrl: "./images/public_health.png" },
        { word: "Health awareness", type: "(n)", mean: "Nhận thức về sức khỏe", example: "Schools play a vital role in raising health awareness among students.", imageUrl: "./images/health_awareness.png" },
        { word: "Medical treatment", type: "(n)", mean: "Điều trị y tế", example: "Patients with severe symptoms should seek immediate medical treatment.", imageUrl: "./images/medical_treatment.png" }
    ],
    "family": [
        { word: "Nuclear family", type: "(n)", mean: "Gia đình hạt nhân", example: "The nuclear family is the most common family structure in modern society.", imageUrl: "./images/nuclear_family.png" },
        { word: "Extended family", type: "(n)", mean: "Gia đình nhiều thế hệ", example: "Growing up in an extended family helps children learn how to share.", imageUrl: "./images/extended_family.png" },
        { word: "Single-parent family", type: "(n)", mean: "Gia đình đơn thân", example: "Financial support is crucial for children in a single-parent family.", imageUrl: "./images/single_parent_family.png" },
        { word: "Household", type: "(n)", mean: "Hộ gia đình", example: "The average size of a household has decreased in recent years.", imageUrl: "./images/household.png" },
        { word: "Breadwinner", type: "(n)", mean: "Trụ cột gia đình", example: "Traditionally, the father was the main breadwinner of the family.", imageUrl: "./images/breadwinner.png" },
        { word: "Dependents", type: "(n)", mean: "Người phụ thuộc", example: "Employees can claim tax deductions if they have dependents.", imageUrl: "./images/dependents.png" },
        { word: "Sibling", type: "(n)", mean: "Anh/chị/em ruột", example: "I have a close relationship with my younger sibling.", imageUrl: "./images/sibling.png" },
        { word: "Only child", type: "(n)", mean: "Con một", example: "Being an only child means you get all of your parents' attention.", imageUrl: "./images/only_child.png" },
        { word: "Generation gap", type: "(n)", mean: "Khoảng cách thế hệ", example: "The generation gap can cause misunderstandings about technology.", imageUrl: "./images/generation_gap.png" },
        { word: "Family-oriented", type: "(adj)", mean: "Coi trọng gia đình", example: "He is a family-oriented man who always prioritizes his children.", imageUrl: "./images/family_oriented.png" },
        { word: "Close-knit", type: "(adj)", mean: "Gắn bó khăng khít", example: "We are a close-knit family and support each other through hard times.", imageUrl: "./images/close_knit.png" },
        { word: "Parental guidance", type: "(n)", mean: "Sự định hướng của cha mẹ", example: "Proper parental guidance is essential for a teenager's development.", imageUrl: "./images/parental_guidance.png" },
        { word: "Emotional support", type: "(n)", mean: "Hỗ trợ tinh thần", example: "Family provides the emotional support needed to overcome stress.", imageUrl: "./images/emotional_support.png" },
        { word: "Mutual respect", type: "(n)", mean: "Sự tôn trọng lẫn nhau", example: "A healthy marriage is built on trust and mutual respect.", imageUrl: "./images/mutual_respect.png" },
        { word: "Family bond", type: "(n)", mean: "Mối liên kết gia đình", example: "Having dinner together every night strengthens the family bond.", imageUrl: "./images/family_bond.png" },
        { word: "Upbringing", type: "(n)", mean: "Sự nuôi dạy", example: "A strict upbringing shaped his disciplined approach to studying.", imageUrl: "./images/upbringing.png" },
        { word: "Discipline", type: "(n)", mean: "Sự kỷ luật", example: "Parents should enforce discipline without using physical punishment.", imageUrl: "./images/discipline.png" },
        { word: "Caregiver", type: "(n)", mean: "Người chăm sóc", example: "The mother is usually the primary caregiver in the early years.", imageUrl: "./images/caregiver.png" },
        { word: "Role model", type: "(n)", mean: "Hình mẫu", example: "Teachers often serve as important role models for their students.", imageUrl: "./images/role_model.png" },
        { word: "Household responsibilities", type: "(n)", mean: "Trách nhiệm trong gia đình", example: "Children should learn to share household responsibilities.", imageUrl: "./images/household_responsibilities.png" },
        { word: "Divorce rate", type: "(n)", mean: "Tỷ lệ ly hôn", example: "The divorce rate has increased due to modern lifestyle pressures.", imageUrl: "./images/divorce_rate.png" },
        { word: "Work-life balance", type: "(n)", mean: "Cân bằng công việc - cuộc sống", example: "Maintaining a healthy work-life balance reduces domestic conflict.", imageUrl: "./images/work_life_balance.png" },
        { word: "Domestic conflict", type: "(n)", mean: "Mâu thuẫn gia đình", example: "Financial issues are a common cause of domestic conflict.", imageUrl: "./images/domestic_conflict.png" },
        { word: "Child neglect", type: "(n)", mean: "Bỏ bê con cái", example: "Child neglect can have severe long-term psychological effects.", imageUrl: "./images/child_neglect.png" },
        { word: "Financial burden", type: "(n)", mean: "Gánh nặng tài chính", example: "University tuition fees can be a huge financial burden for families.", imageUrl: "./images/financial_burden.png" },
        { word: "Parenting style", type: "(n)", mean: "Phong cách nuôi dạy con", example: "Different cultures have completely different parenting styles.", imageUrl: "./images/parenting_style.png" },
        { word: "Generation differences", type: "(n)", mean: "Khác biệt thế hệ", example: "Generation differences are most obvious in musical tastes.", imageUrl: "./images/generation_differences.png" },
        { word: "Aging population", type: "(n)", mean: "Dân số già hóa", example: "An aging population puts pressure on the healthcare system.", imageUrl: "./images/aging_population.png" },
        { word: "Family values", type: "(n)", mean: "Giá trị gia đình", example: "Traditional family values are still respected in many Asian societies.", imageUrl: "./images/family_values.png" },
        { word: "Quality time", type: "(n)", mean: "Thời gian chất lượng", example: "Spending quality time with children is more important than buying them gifts.", imageUrl: "./images/quality_time.png" }
    ],
    "travel": [
        { word: "Domestic travel", type: "(n)", mean: "Du lịch trong nước", example: "Domestic travel has recovered faster than international flights.", imageUrl: "./images/domestic_travel.png" },
        { word: "International travel", type: "(n)", mean: "Du lịch quốc tế", example: "International travel exposes you to different cultures and languages.", imageUrl: "./images/international_travel.png" },
        { word: "Eco-tourism", type: "(n)", mean: "Du lịch sinh thái", example: "Eco-tourism helps protect the environment and supports local communities.", imageUrl: "./images/eco_tourism.png" },
        { word: "Mass tourism", type: "(n)", mean: "Du lịch đại trà", example: "Mass tourism can cause severe damage to historical sites.", imageUrl: "./images/mass_tourism.png" },
        { word: "Backpacking", type: "(n)", mean: "Du lịch bụi", example: "Backpacking is a popular way for students to explore the world cheaply.", imageUrl: "./images/backpacking.png" },
        { word: "Package tour", type: "(n)", mean: "Tour trọn gói", example: "Many older people prefer the convenience of a package tour.", imageUrl: "./images/package_tour.png" },
        { word: "Solo travel", type: "(n)", mean: "Du lịch một mình", example: "Solo travel forces you to step out of your comfort zone.", imageUrl: "./images/solo_travel.png" },
        { word: "Business trip", type: "(n)", mean: "Chuyến công tác", example: "Engineers often go on business trips to inspect new facilities.", imageUrl: "./images/business_trip.png" },
        { word: "Long-haul flight", type: "(n)", mean: "Chuyến bay đường dài", example: "Make sure to drink plenty of water during a long-haul flight.", imageUrl: "./images/long_haul_flight.png" },
        { word: "Short getaway", type: "(n)", mean: "Chuyến đi ngắn ngày", example: "We went on a short getaway to the mountains to relax.", imageUrl: "./images/short_getaway.png" },
        { word: "Itinerary", type: "(n)", mean: "Lịch trình", example: "Our itinerary includes a visit to the local museum.", imageUrl: "./images/itinerary.png" },
        { word: "Accommodation", type: "(n)", mean: "Chỗ ở", example: "Booking accommodation in advance is highly recommended.", imageUrl: "./images/accommodation.png" },
        { word: "Hospitality", type: "(n)", mean: "Sự hiếu khách", example: "The locals are famous for their warm hospitality.", imageUrl: "./images/hospitality.png" },
        { word: "Tourist attraction", type: "(n)", mean: "Điểm du lịch", example: "The Eiffel Tower is a major tourist attraction in Paris.", imageUrl: "./images/tourist_attraction.png" },
        { word: "Scenic views", type: "(n)", mean: "Cảnh đẹp", example: "The hotel room offers stunning scenic views of the ocean.", imageUrl: "./images/scenic_views.png" },
        { word: "Local cuisine", type: "(n)", mean: "Ẩm thực địa phương", example: "Trying the local cuisine is an essential part of any trip.", imageUrl: "./images/local_cuisine.png" },
        { word: "Cultural experience", type: "(n)", mean: "Trải nghiệm văn hóa", example: "Attending the festival was a fantastic cultural experience.", imageUrl: "./images/cultural_experience.png" },
        { word: "Travel insurance", type: "(n)", mean: "Bảo hiểm du lịch", example: "You should always buy travel insurance before going abroad.", imageUrl: "./images/travel_insurance.png" },
        { word: "Jet lag", type: "(n)", mean: "Lệch múi giờ", example: "It took me three days to recover from the jet lag.", imageUrl: "./images/jet_lag.png" },
        { word: "Travel essentials", type: "(n)", mean: "Vật dụng cần thiết", example: "A passport and a charger are absolute travel essentials.", imageUrl: "./images/travel_essentials.png" },
        { word: "Overcrowding", type: "(n)", mean: "Quá tải", example: "Overcrowding in famous cities ruins the experience for many visitors.", imageUrl: "./images/overcrowding.png" },
        { word: "Tourist hotspot", type: "(n)", mean: "Điểm du lịch nổi tiếng", example: "During summer, the beach becomes a busy tourist hotspot.", imageUrl: "./images/tourist_hotspot.png" },
        { word: "Environmental impact", type: "(n)", mean: "Tác động môi trường", example: "Air travel has a significant environmental impact.", imageUrl: "./images/environmental_impact.png" },
        { word: "Sustainable tourism", type: "(n)", mean: "Du lịch bền vững", example: "Sustainable tourism minimizes carbon emissions and waste.", imageUrl: "./images/sustainable_tourism.png" },
        { word: "Cultural preservation", type: "(n)", mean: "Bảo tồn văn hóa", example: "Tourism revenue can be used for cultural preservation.", imageUrl: "./images/cultural_preservation.png" },
        { word: "Travel restrictions", type: "(n)", mean: "Hạn chế đi lại", example: "New travel restrictions were implemented due to the virus outbreak.", imageUrl: "./images/travel_restrictions.png" },
        { word: "Carbon emissions", type: "(n)", mean: "Khí thải carbon", example: "Aviation contributes heavily to global carbon emissions.", imageUrl: "./images/carbon_emissions.png" },
        { word: "Tourism industry", type: "(n)", mean: "Ngành du lịch", example: "The tourism industry provides millions of jobs worldwide.", imageUrl: "./images/tourism_industry.png" },
        { word: "Economic boost", type: "(n)", mean: "Thúc đẩy kinh tế", example: "Hosting the Olympics provided a major economic boost for the city.", imageUrl: "./images/economic_boost.png" },
        { word: "Peak season", type: "(n)", mean: "Mùa cao điểm", example: "Flights and hotels are much more expensive during the peak season.", imageUrl: "./images/peak_season.png" }
    ],
    "technology": [
        { word: "Cutting-edge technology", type: "(n)", mean: "Công nghệ tiên tiến", example: "The laboratory is equipped with cutting-edge technology.", imageUrl: "./images/cutting_edge_technology.png" },
        { word: "Technological advancement", type: "(n)", mean: "Tiến bộ công nghệ", example: "Technological advancement has dramatically changed how we study.", imageUrl: "./images/technological_advancement.png" },
        { word: "Digital transformation", type: "(n)", mean: "Chuyển đổi số", example: "Many businesses underwent rapid digital transformation recently.", imageUrl: "./images/digital_transformation.png" },
        { word: "Innovation", type: "(n)", mean: "Đổi mới", example: "Innovation is key to surviving in a competitive market.", imageUrl: "./images/innovation_tech.png" },
        { word: "Automation", type: "(n)", mean: "Tự động hóa", example: "Automation is highly applied in modern thermal and mechanical systems.", imageUrl: "./images/automation.png" },
        { word: "Artificial intelligence", type: "(n)", mean: "Trí tuệ nhân tạo", example: "Artificial intelligence is capable of solving complex engineering problems.", imageUrl: "./images/artificial_intelligence.png" },
        { word: "Machine learning", type: "(n)", mean: "Học máy", example: "Machine learning algorithms improve themselves through experience.", imageUrl: "./images/machine_learning.png" },
        { word: "Data analytics", type: "(n)", mean: "Phân tích dữ liệu", example: "Data analytics helps companies understand consumer behavior.", imageUrl: "./images/data_analytics.png" },
        { word: "Cloud computing", type: "(n)", mean: "Điện toán đám mây", example: "Cloud computing allows us to access files from anywhere.", imageUrl: "./images/cloud_computing.png" },
        { word: "Cybersecurity", type: "(n)", mean: "An ninh mạng", example: "Cybersecurity is crucial to protect sensitive personal information.", imageUrl: "./images/cybersecurity.png" },
        { word: "Smart device", type: "(n)", mean: "Thiết bị thông minh", example: "Almost every student now owns at least one smart device.", imageUrl: "./images/smart_device.png" },
        { word: "High-speed internet", type: "(n)", mean: "Internet tốc độ cao", example: "High-speed internet is essential for uninterrupted virtual meetings.", imageUrl: "./images/high_speed_internet.png" },
        { word: "Social media platforms", type: "(n)", mean: "Nền tảng mạng xã hội", example: "Social media platforms can be highly addictive for teenagers.", imageUrl: "./images/social_media_platforms.png" },
        { word: "Online privacy", type: "(n)", mean: "Quyền riêng tư trực tuyến", example: "Users must be careful about their online privacy settings.", imageUrl: "./images/online_privacy.png" },
        { word: "Data breach", type: "(n)", mean: "Rò rỉ dữ liệu", example: "A recent data breach exposed the passwords of millions of users.", imageUrl: "./images/data_breach.png" },
        { word: "Digital footprint", type: "(n)", mean: "Dấu vết số", example: "Employers often research a candidate's digital footprint.", imageUrl: "./images/digital_footprint.png" },
        { word: "Screen time", type: "(n)", mean: "Thời gian dùng màn hình", example: "Parents should limit their children's daily screen time.", imageUrl: "./images/screen_time.png" },
        { word: "Internet addiction", type: "(n)", mean: "Nghiện internet", example: "Internet addiction can severely affect academic performance.", imageUrl: "./images/internet_addiction.png" },
        { word: "Virtual meeting", type: "(n)", mean: "Họp trực tuyến", example: "Virtual meetings save a lot of time and travel expenses.", imageUrl: "./images/virtual_meeting.png" },
        { word: "Remote work", type: "(n)", mean: "Làm việc từ xa", example: "Remote work offers flexibility but requires strong self-discipline.", imageUrl: "./images/remote_work.png" },
        { word: "Job displacement", type: "(n)", mean: "Mất việc do công nghệ", example: "Automation in factories often leads to job displacement.", imageUrl: "./images/job_displacement.png" },
        { word: "Digital divide", type: "(n)", mean: "Khoảng cách số", example: "The government must invest in education to bridge the digital divide.", imageUrl: "./images/digital_divide.png" },
        { word: "Information overload", type: "(n)", mean: "Quá tải thông tin", example: "Constant notifications can easily cause information overload.", imageUrl: "./images/information_overload.png" },
        { word: "Technological dependency", type: "(n)", mean: "Phụ thuộc công nghệ", example: "Technological dependency makes us vulnerable to system failures.", imageUrl: "./images/technological_dependency.png" },
        { word: "Privacy concerns", type: "(n)", mean: "Lo ngại quyền riêng tư", example: "The new tracking app has raised serious privacy concerns.", imageUrl: "./images/privacy_concerns.png" },
        { word: "Ethical issues", type: "(n)", mean: "Vấn đề đạo đức", example: "Cloning technology brings up many complex ethical issues.", imageUrl: "./images/ethical_issues.png" },
        { word: "Automation risk", type: "(n)", mean: "Rủi ro tự động hóa", example: "Manual laborers face the highest automation risk.", imageUrl: "./images/automation_risk.png" },
        { word: "Productivity boost", type: "(n)", mean: "Tăng năng suất", example: "New software provided a significant productivity boost for the team.", imageUrl: "./images/productivity_boost.png" },
        { word: "User-friendly", type: "(adj)", mean: "Thân thiện người dùng", example: "The interface of the application is designed to be user-friendly.", imageUrl: "./images/user_friendly.png" },
        { word: "Time-consuming", type: "(adj)", mean: "Tốn thời gian", example: "Processing large datasets manually is incredibly time-consuming.", imageUrl: "./images/time_consuming.png" }
    ],
    "sports": [
        { word: "Competitive sports", type: "(n)", mean: "Thể thao thi đấu", example: "Participating in competitive sports teaches children how to handle loss.", imageUrl: "./images/competitive_sports.png" },
        { word: "Team sports", type: "(n)", mean: "Thể thao đồng đội", example: "Team sports like basketball develop strong communication skills.", imageUrl: "./images/team_sports.png" },
        { word: "Individual sports", type: "(n)", mean: "Thể thao cá nhân", example: "Individual sports require a high degree of self-motivation.", imageUrl: "./images/individual_sports.png" },
        { word: "Extreme sports", type: "(n)", mean: "Thể thao mạo hiểm", example: "Extreme sports carry a high risk of serious injury.", imageUrl: "./images/extreme_sports.png" },
        { word: "Water sports", type: "(n)", mean: "Thể thao dưới nước", example: "Surfing and diving are popular water sports in coastal areas.", imageUrl: "./images/water_sports.png" },
        { word: "Indoor sports", type: "(n)", mean: "Thể thao trong nhà", example: "Badminton is one of the most common indoor sports.", imageUrl: "./images/indoor_sports.png" },
        { word: "Outdoor activities", type: "(n)", mean: "Hoạt động ngoài trời", example: "Hiking and camping are great outdoor activities for the weekend.", imageUrl: "./images/outdoor_activities.png" },
        { word: "Physical activity", type: "(n)", mean: "Hoạt động thể chất", example: "Daily physical activity is necessary to maintain good health.", imageUrl: "./images/physical_activity.png" },
        { word: "Recreational sports", type: "(n)", mean: "Thể thao giải trí", example: "Many people play recreational sports simply to relieve stress.", imageUrl: "./images/recreational_sports.png" },
        { word: "Professional athlete", type: "(n)", mean: "Vận động viên chuyên nghiệp", example: "A professional athlete must follow a strict diet and training regime.", imageUrl: "./images/professional_athlete.png" },
        { word: "Physical endurance", type: "(n)", mean: "Sức bền", example: "Marathon runners need incredible physical endurance.", imageUrl: "./images/physical_endurance.png" },
        { word: "Muscle strength", type: "(n)", mean: "Sức mạnh cơ bắp", example: "Weightlifting is designed to increase muscle strength.", imageUrl: "./images/muscle_strength.png" },
        { word: "Stamina", type: "(n)", mean: "Thể lực", example: "You need good stamina to play a full 90-minute football match.", imageUrl: "./images/stamina.png" },
        { word: "Intensive training", type: "(n)", mean: "Luyện tập cường độ cao", example: "The team underwent intensive training before the championship.", imageUrl: "./images/intensive_training.png" },
        { word: "Workout routine", type: "(n)", mean: "Lịch tập", example: "Sticking to a daily workout routine yields the best results.", imageUrl: "./images/workout_routine.png" },
        { word: "Fitness level", type: "(n)", mean: "Mức thể lực", example: "The exercises can be adjusted to suit your personal fitness level.", imageUrl: "./images/fitness_level.png" },
        { word: "Warm-up", type: "(n/v)", mean: "Khởi động", example: "A proper warm-up prevents muscle cramps during exercise.", imageUrl: "./images/warm_up.png" },
        { word: "Cool down", type: "(n/v)", mean: "Thả lỏng", example: "It is important to cool down and stretch after a heavy workout.", imageUrl: "./images/cool_down.png" },
        { word: "Injury prevention", type: "(n)", mean: "Phòng tránh chấn thương", example: "Wearing the right shoes is crucial for injury prevention.", imageUrl: "./images/injury_prevention.png" },
        { word: "Personal trainer", type: "(n)", mean: "Huấn luyện viên cá nhân", example: "A personal trainer can help correct your lifting posture.", imageUrl: "./images/personal_trainer.png" },
        { word: "Boost immunity", type: "(v)", mean: "Tăng miễn dịch", example: "Regular exercise helps boost immunity against common illnesses.", imageUrl: "./images/boost_immunity.png" },
        { word: "Mental well-being", type: "(n)", mean: "Sức khỏe tinh thần", example: "Sports have a profoundly positive impact on mental well-being.", imageUrl: "./images/mental_well_being.png" },
        { word: "Stress relief", type: "(n)", mean: "Giảm căng thẳng", example: "Swimming serves as an excellent form of stress relief.", imageUrl: "./images/stress_relief.png" },
        { word: "Sedentary lifestyle", type: "(n)", mean: "Lối sống ít vận động", example: "A sedentary lifestyle is a major cause of modern health problems.", imageUrl: "./images/sedentary_lifestyle.png" },
        { word: "Sportsmanship", type: "(n)", mean: "Tinh thần thể thao", example: "Shaking hands after a match is a sign of good sportsmanship.", imageUrl: "./images/sportsmanship.png" },
        { word: "Fair play", type: "(n)", mean: "Chơi đẹp", example: "Referees are there to ensure fair play on the field.", imageUrl: "./images/fair_play.png" },
        { word: "Performance-enhancing drugs", type: "(n)", mean: "Chất kích thích", example: "Using performance-enhancing drugs will result in a lifetime ban.", imageUrl: "./images/performance_enhancing_drugs.png" },
        { word: "Match-fixing", type: "(n)", mean: "Dàn xếp tỉ số", example: "Several players were investigated for suspected match-fixing.", imageUrl: "./images/match_fixing.png" },
        { word: "Fan base", type: "(n)", mean: "Lượng người hâm mộ", example: "The football club has a massive international fan base.", imageUrl: "./images/fan_base.png" },
        { word: "Sports industry", type: "(n)", mean: "Ngành thể thao", example: "The global sports industry generates billions of dollars annually.", imageUrl: "./images/sports_industry.png" }
    ],
    "music": [
        { word: "Classical music", type: "(n)", mean: "Nhạc cổ điển", example: "Listening to classical music can help improve concentration.", imageUrl: "./images/classical_music.png" },
        { word: "Pop music", type: "(n)", mean: "Nhạc pop", example: "Pop music usually features catchy melodies and simple lyrics.", imageUrl: "./images/pop_music.png" },
        { word: "Rock music", type: "(n)", mean: "Nhạc rock", example: "Rock music is characterized by heavy beats and electric guitars.", imageUrl: "./images/rock_music.png" },
        { word: "Jazz", type: "(n)", mean: "Nhạc jazz", example: "Jazz is a genre that relies heavily on instrumental improvisation.", imageUrl: "./images/jazz.png" },
        { word: "Hip-hop", type: "(n)", mean: "Hip hop", example: "Hip-hop culture has deeply influenced modern fashion trends.", imageUrl: "./images/hip_hop.png" },
        { word: "Electronic music", type: "(n)", mean: "Nhạc điện tử", example: "Electronic music is very popular in nightclubs and festivals.", imageUrl: "./images/electronic_music.png" },
        { word: "Folk music", type: "(n)", mean: "Nhạc dân gian", example: "Folk music often tells stories about the daily lives of ordinary people.", imageUrl: "./images/folk_music.png" },
        { word: "Traditional music", type: "(n)", mean: "Nhạc truyền thống", example: "Traditional music is an integral part of national identity.", imageUrl: "./images/traditional_music.png" },
        { word: "Instrumental music", type: "(n)", mean: "Nhạc không lời", example: "Many students prefer studying while listening to instrumental music.", imageUrl: "./images/instrumental_music.png" },
        { word: "Live music", type: "(n)", mean: "Nhạc trực tiếp", example: "The atmosphere of a live music concert is truly electrifying.", imageUrl: "./images/live_music.png" },
        { word: "Melody", type: "(n)", mean: "Giai điệu", example: "The song has a beautiful and melancholic melody.", imageUrl: "./images/melody.png" },
        { word: "Rhythm", type: "(n)", mean: "Nhịp điệu", example: "You naturally want to dance when you hear a strong rhythm.", imageUrl: "./images/rhythm.png" },
        { word: "Lyrics", type: "(n)", mean: "Lời bài hát", example: "The lyrics of this song convey a powerful message about love.", imageUrl: "./images/lyrics.png" },
        { word: "Harmony", type: "(n)", mean: "Hòa âm", example: "The two singers' voices blended in perfect harmony.", imageUrl: "./images/harmony.png" },
        { word: "Vocal range", type: "(n)", mean: "Quãng giọng", example: "She is famous for her impressive vocal range.", imageUrl: "./images/vocal_range.png" },
        { word: "Pitch", type: "(n)", mean: "Cao độ", example: "The singer struggled to hit the high pitch during the chorus.", imageUrl: "./images/pitch.png" },
        { word: "Tone", type: "(n)", mean: "Âm sắc", example: "His voice has a very warm and soothing tone.", imageUrl: "./images/tone.png" },
        { word: "Composition", type: "(n)", mean: "Sáng tác", example: "This musical composition was written in the 18th century.", imageUrl: "./images/composition.png" },
        { word: "Live performance", type: "(n)", mean: "Biểu diễn trực tiếp", example: "A live performance allows artists to connect with their fans.", imageUrl: "./images/live_performance.png" },
        { word: "Music festival", type: "(n)", mean: "Lễ hội âm nhạc", example: "Thousands of young people gather for the outdoor music festival.", imageUrl: "./images/music_festival.png" },
        { word: "Music industry", type: "(n)", mean: "Ngành âm nhạc", example: "The internet has completely transformed the music industry.", imageUrl: "./images/music_industry.png" },
        { word: "Streaming platform", type: "(n)", mean: "Nền tảng nghe nhạc", example: "Artists now earn most of their revenue through streaming platforms.", imageUrl: "./images/streaming_platform.png" },
        { word: "Digital download", type: "(n)", mean: "Tải nhạc", example: "Sales of physical CDs have fallen due to digital downloads.", imageUrl: "./images/digital_download.png" },
        { word: "Copyright infringement", type: "(n)", mean: "Vi phạm bản quyền", example: "Sharing music files for free is considered copyright infringement.", imageUrl: "./images/copyright_infringement.png" },
        { word: "Musical taste", type: "(n)", mean: "Gu âm nhạc", example: "People's musical taste often changes as they grow older.", imageUrl: "./images/musical_taste.png" },
        { word: "Emotional expression", type: "(n)", mean: "Biểu đạt cảm xúc", example: "Music is a universal language for emotional expression.", imageUrl: "./images/emotional_expression.png" },
        { word: "Stress relief", type: "(n)", mean: "Giảm stress", example: "Playing an instrument provides an excellent outlet for stress relief.", imageUrl: "./images/stress_relief_music.png" },
        { word: "Cultural identity", type: "(n)", mean: "Bản sắc văn hóa", example: "Indigenous music helps preserve a community's cultural identity.", imageUrl: "./images/cultural_identity.png" },
        { word: "Global audience", type: "(n)", mean: "Khán giả toàn cầu", example: "K-pop has successfully reached a massive global audience.", imageUrl: "./images/global_audience.png" },
        { word: "Commercial success", type: "(n)", mean: "Thành công thương mại", example: "Despite critical backlash, the album was a huge commercial success.", imageUrl: "./images/commercial_success.png" }
    ]
};
    